import { G as Grants } from './grants-Bl8lIEzI.js';
import { F as Filter } from './filter-BBRpwKD3.js';

/**
 * Generated by orval 🍺
 * Do not edit manually.
 * api API
 * OpenAPI spec version: 1.0
 */
type UserCustomProperties = {
    [key: string]: unknown;
};

/**
 * Generated by orval 🍺
 * Do not edit manually.
 * api API
 * OpenAPI spec version: 1.0
 */
interface ContactDetails {
    email?: string;
    phoneNumber?: string;
}

/**
 * Generated by orval 🍺
 * Do not edit manually.
 * api API
 * OpenAPI spec version: 1.0
 */
type RoleDefinitionCustomProperties = {
    [key: string]: unknown;
};

/**
 * Generated by orval 🍺
 * Do not edit manually.
 * api API
 * OpenAPI spec version: 1.0
 */
type RoleDefinitionEntityPermissions = {
    [key: string]: string[];
};

/**
 * Generated by orval 🍺
 * Do not edit manually.
 * api API
 * OpenAPI spec version: 1.0
 */
type ConnectorPermissionsCustomProperties = {
    [key: string]: unknown;
};

/**
 * Generated by orval 🍺
 * Do not edit manually.
 * api API
 * OpenAPI spec version: 1.0
 */
interface ConnectorResources {
    triggers?: string[];
    actions?: string[];
}

/**
 * Generated by orval 🍺
 * Do not edit manually.
 * api API
 * OpenAPI spec version: 1.0
 */

interface ConnectorPermissions {
    version?: number;
    createdTime?: number;
    modifiedTime?: number;
    lastPlatformUpdateOn?: number;
    lastPlatformUpdateBy?: number;
    ownerUserId?: number;
    lastModifiedBy?: number;
    deleted?: boolean;
    grants?: Grants;
    flattenedGrants?: string[];
    projectId?: number;
    spaceId?: string;
    tags?: string[];
    standard?: boolean;
    customProperties?: ConnectorPermissionsCustomProperties;
    id?: string;
    appName?: string;
    roleDefId?: string;
    resources?: ConnectorResources;
    connectionPermissions?: string[];
}

/**
 * Generated by orval 🍺
 * Do not edit manually.
 * api API
 * OpenAPI spec version: 1.0
 */
type EntityTypePermissionsCustomProperties = {
    [key: string]: unknown;
};

/**
 * Generated by orval 🍺
 * Do not edit manually.
 * api API
 * OpenAPI spec version: 1.0
 */

interface EntityTypePermissions {
    version?: number;
    createdTime?: number;
    modifiedTime?: number;
    lastPlatformUpdateOn?: number;
    lastPlatformUpdateBy?: number;
    ownerUserId?: number;
    lastModifiedBy?: number;
    deleted?: boolean;
    grants?: Grants;
    flattenedGrants?: string[];
    projectId?: number;
    spaceId?: string;
    tags?: string[];
    standard?: boolean;
    customProperties?: EntityTypePermissionsCustomProperties;
    id?: string;
    entityTypeId?: string;
    roleDefId?: string;
    permissions?: string[];
}

/**
 * Generated by orval 🍺
 * Do not edit manually.
 * api API
 * OpenAPI spec version: 1.0
 */

interface RoleDefinition {
    lcName?: string;
    lastModifiedBy?: number;
    modifiedTime?: number;
    ownerUserId?: number;
    createdTime?: number;
    version?: number;
    lastPlatformUpdateOn?: number;
    lastPlatformUpdateBy?: number;
    deleted?: boolean;
    grants?: Grants;
    flattenedGrants?: string[];
    projectId?: number;
    spaceId?: string;
    tags?: string[];
    standard?: boolean;
    customProperties?: RoleDefinitionCustomProperties;
    id?: string;
    /** @pattern \S */
    name: string;
    description?: string;
    entityPermissions?: RoleDefinitionEntityPermissions;
    standardRole?: boolean;
    connectorsEnablement?: string;
    entityTypeEnablement?: string;
    applicationId?: string;
    state?: string;
    connectorPermissions?: ConnectorPermissions[];
    entityTypePermissions?: EntityTypePermissions[];
}

/**
 * Generated by orval 🍺
 * Do not edit manually.
 * api API
 * OpenAPI spec version: 1.0
 */
type UserGroupCustomProperties = {
    [key: string]: unknown;
};

/**
 * Generated by orval 🍺
 * Do not edit manually.
 * api API
 * OpenAPI spec version: 1.0
 */

interface UserGroup {
    lcName?: string;
    lastModifiedBy?: number;
    modifiedTime?: number;
    ownerUserId?: number;
    createdTime?: number;
    version?: number;
    lastPlatformUpdateOn?: number;
    lastPlatformUpdateBy?: number;
    deleted?: boolean;
    grants?: Grants;
    flattenedGrants?: string[];
    projectId?: number;
    spaceId?: string;
    tags?: string[];
    customProperties?: UserGroupCustomProperties;
    id?: string;
    /** @pattern \S */
    name: string;
    description?: string;
    criteria?: Filter;
    userCount?: number;
    userIds?: string[];
    applicationId?: string;
    standard?: boolean;
    allowNotification?: boolean;
    allRecordsShared?: boolean;
    criteriaStr?: string;
    criteriaFields?: string[];
}

/**
 * Generated by orval 🍺
 * Do not edit manually.
 * api API
 * OpenAPI spec version: 1.0
 */
type UserLoginDetails = {
    [key: string]: unknown;
};

/**
 * Generated by orval 🍺
 * Do not edit manually.
 * api API
 * OpenAPI spec version: 1.0
 */

interface User {
    lcName?: string;
    createdTime?: number;
    version?: number;
    modifiedTime?: number;
    lastPlatformUpdateOn?: number;
    lastPlatformUpdateBy?: number;
    ownerUserId?: number;
    lastModifiedBy?: number;
    deleted?: boolean;
    grants?: Grants;
    flattenedGrants?: string[];
    projectId?: number;
    spaceId?: string;
    tags?: string[];
    standard?: boolean;
    customProperties?: UserCustomProperties;
    id?: string;
    username?: string;
    name?: string;
    contactDetails?: ContactDetails;
    password?: string;
    initialCustomerId?: number;
    lastLoginAt?: number;
    applicationId?: string;
    staticUserGroups?: string[];
    dynamicUserGroups?: string[];
    ssoLogin?: boolean;
    state?: string;
    locale?: string;
    firstLogin?: boolean;
    testUser?: boolean;
    roleIds?: string[];
    roles?: RoleDefinition[];
    teams?: UserGroup[];
    idp?: string;
    loginDetails?: UserLoginDetails;
    email?: string;
    phoneNumber?: string;
    userGroups?: string[];
    userId?: number;
}

/**
 * Generated by orval 🍺
 * Do not edit manually.
 * api API
 * OpenAPI spec version: 1.0
 */
type CustomerCustomProperties = {
    [key: string]: unknown;
};

/**
 * Generated by orval 🍺
 * Do not edit manually.
 * api API
 * OpenAPI spec version: 1.0
 */

interface Customer {
    version?: number;
    createdTime?: number;
    modifiedTime?: number;
    lastPlatformUpdateOn?: number;
    lastPlatformUpdateBy?: number;
    ownerUserId?: number;
    lastModifiedBy?: number;
    deleted?: boolean;
    grants?: Grants;
    flattenedGrants?: string[];
    projectId?: number;
    spaceId?: string;
    tags?: string[];
    standard?: boolean;
    customProperties?: CustomerCustomProperties;
    id?: string;
    name?: string;
    sourceCustomer?: string;
}

/**
 * Generated by orval 🍺
 * Do not edit manually.
 * api API
 * OpenAPI spec version: 1.0
 */
interface ModuleConfig {
    id?: string;
    displayName?: string;
    enabled?: boolean;
}

/**
 * Generated by orval 🍺
 * Do not edit manually.
 * api API
 * OpenAPI spec version: 1.0
 */

interface CurrentUserDetails {
    user?: User;
    customer?: Customer;
    assumeContextAllowed?: boolean;
    modules?: ModuleConfig[];
    environment?: string;
    notificationMqttTopics?: string[];
}

export type { CurrentUserDetails as C };
