import { S as SimpleOps, C as CompoundOps, R as ResolvedFilter, a as SchemaAndLayout, b as Schema } from './schema-CHL6CK9Q.js';

/**
 * Generated by orval 🍺
 * Do not edit manually.
 * api API
 * OpenAPI spec version: 1.0
 */
type ExecuteWorkflowNodeResponseLookupReferences = {
    [key: string]: unknown;
};

/**
 * Generated by orval 🍺
 * Do not edit manually.
 * api API
 * OpenAPI spec version: 1.0
 */

interface ExecuteWorkflowNodeResponse {
    id?: string;
    response?: unknown;
    lookupReferences?: ExecuteWorkflowNodeResponseLookupReferences;
    executionInstanceId?: string;
}

/**
 * Generated by orval 🍺
 * Do not edit manually.
 * api API
 * OpenAPI spec version: 1.0
 */
type ExecuteWorkflowNodeRequestContext = {
    [key: string]: unknown;
};

/**
 * Generated by orval 🍺
 * Do not edit manually.
 * api API
 * OpenAPI spec version: 1.0
 */
type ExecuteWorkflowNodeRequestInputs = {
    [key: string]: unknown;
};

/**
 * Generated by orval 🍺
 * Do not edit manually.
 * api API
 * OpenAPI spec version: 1.0
 */
type LookupRequestOptions = {
    [key: string]: unknown;
};

/**
 * Generated by orval 🍺
 * Do not edit manually.
 * api API
 * OpenAPI spec version: 1.0
 */

interface LookupRequest {
    name?: string;
    type?: string;
    lookupType?: string;
    options?: LookupRequestOptions;
    fields?: string[];
}

/**
 * Generated by orval 🍺
 * Do not edit manually.
 * api API
 * OpenAPI spec version: 1.0
 */
type FilterBlockStringDetails = {
    [key: string]: unknown;
};

/**
 * Generated by orval 🍺
 * Do not edit manually.
 * api API
 * OpenAPI spec version: 1.0
 */

interface FilterBlockString {
    operator?: SimpleOps;
    value?: string;
    details?: FilterBlockStringDetails;
}

/**
 * Generated by orval 🍺
 * Do not edit manually.
 * api API
 * OpenAPI spec version: 1.0
 */
type UIFilterDetails = {
    [key: string]: unknown;
};

/**
 * Generated by orval 🍺
 * Do not edit manually.
 * api API
 * OpenAPI spec version: 1.0
 */

interface UIFilter {
    operator?: CompoundOps;
    filters?: UIFilter[];
    property?: string;
    filter?: FilterBlockString;
    resolvedFilter?: ResolvedFilter;
    details?: UIFilterDetails;
}

/**
 * Generated by orval 🍺
 * Do not edit manually.
 * api API
 * OpenAPI spec version: 1.0
 */

interface CacheConfig {
    enabled?: boolean;
    timeToLive?: string;
    cacheKey?: string;
    filter?: UIFilter;
    usagePolicy?: string;
    useInMemoryCache?: boolean;
}

/**
 * Generated by orval 🍺
 * Do not edit manually.
 * api API
 * OpenAPI spec version: 1.0
 */

interface RetryConfig1 {
    enabled?: boolean;
    /**
     * @minimum 0
     * @maximum 5
     */
    count?: number;
    /** @minimum 0 */
    initialDelay?: number;
    /** @minimum 0 */
    maxDelay?: number;
    /**
     * @minimum 1
     * @maximum 5
     */
    backOffFactor?: number;
    captureRetries?: boolean;
    filter?: UIFilter;
}

/**
 * Generated by orval 🍺
 * Do not edit manually.
 * api API
 * OpenAPI spec version: 1.0
 */

interface RateLimitConfig1 {
    enabled?: boolean;
    threshold?: string;
    duration?: string;
    unit?: string;
    waitForNextWindow?: boolean;
    filter?: UIFilter;
    key?: string;
    incrementParameter?: string;
}

/**
 * Generated by orval 🍺
 * Do not edit manually.
 * api API
 * OpenAPI spec version: 1.0
 */

interface RateLimitConfigWrapper1 {
    enabled?: boolean;
    rateLimitConfigs?: RateLimitConfig1[];
}

/**
 * Generated by orval 🍺
 * Do not edit manually.
 * api API
 * OpenAPI spec version: 1.0
 */
interface CircuitBreakerConfiguration {
    enabled?: boolean;
    configId?: string;
    failureRateThreshold?: number;
    slowCallRateThreshold?: number;
    slowCallDurationThresholdMillis?: number;
    slidingWindowType?: string;
    slidingWindowSize?: number;
    permittedNumberOfCallsInHalfOpenState?: number;
    maxWaitDurationInHalfOpenState?: number;
    minimumNumberOfCalls?: number;
    waitDurationInOpenState?: number;
    automaticTransitionFromOpenToHalfOpen?: boolean;
}

/**
 * Generated by orval 🍺
 * Do not edit manually.
 * api API
 * OpenAPI spec version: 1.0
 */
interface BusinessHoursConfig {
    enabled?: boolean;
    businessHoursId?: string;
    waitForNextWindow?: boolean;
}

/**
 * Generated by orval 🍺
 * Do not edit manually.
 * api API
 * OpenAPI spec version: 1.0
 */
type WorkflowHookParameters = {
    [key: string]: unknown;
};

/**
 * Generated by orval 🍺
 * Do not edit manually.
 * api API
 * OpenAPI spec version: 1.0
 */

interface WorkflowHook {
    workflowId?: string;
    parameters?: WorkflowHookParameters;
    continueOnFailure?: boolean;
}

/**
 * Generated by orval 🍺
 * Do not edit manually.
 * api API
 * OpenAPI spec version: 1.0
 */

interface HookConfig {
    enabled?: boolean;
    preHooks?: WorkflowHook[];
    postHooks?: WorkflowHook[];
}

/**
 * Generated by orval 🍺
 * Do not edit manually.
 * api API
 * OpenAPI spec version: 1.0
 */

interface LogPolicy {
    level?: string;
    message?: string;
    maskedFields?: string[];
    filter?: UIFilter;
    onlyOnFailure?: boolean;
}

/**
 * Generated by orval 🍺
 * Do not edit manually.
 * api API
 * OpenAPI spec version: 1.0
 */

interface LogConfig {
    enabled?: boolean;
    logPolicies?: LogPolicy[];
}

/**
 * Generated by orval 🍺
 * Do not edit manually.
 * api API
 * OpenAPI spec version: 1.0
 */
type WorkflowNodeMetricTypes = (typeof WorkflowNodeMetricTypes)[keyof typeof WorkflowNodeMetricTypes];
declare const WorkflowNodeMetricTypes: {
    readonly WORKFLOW_NODE_EXECUTION: "WORKFLOW_NODE_EXECUTION";
    readonly WORKFLOW_NODE_EXECUTION_DURATION: "WORKFLOW_NODE_EXECUTION_DURATION";
};

/**
 * Generated by orval 🍺
 * Do not edit manually.
 * api API
 * OpenAPI spec version: 1.0
 */
interface Tag {
    key?: string;
    value?: string;
}

/**
 * Generated by orval 🍺
 * Do not edit manually.
 * api API
 * OpenAPI spec version: 1.0
 */
type Type = (typeof Type)[keyof typeof Type];
declare const Type: {
    readonly COUNTER: "COUNTER";
    readonly TIMER: "TIMER";
    readonly GAUGE: "GAUGE";
    readonly HISTOGRAM: "HISTOGRAM";
};

/**
 * Generated by orval 🍺
 * Do not edit manually.
 * api API
 * OpenAPI spec version: 1.0
 */

interface WorkflowNodeMetricConfig {
    name?: string;
    metricType?: WorkflowNodeMetricTypes;
    eventType?: string;
    tags?: Tag[];
    buckets?: number[];
    baseMetricType?: Type;
}

/**
 * Generated by orval 🍺
 * Do not edit manually.
 * api API
 * OpenAPI spec version: 1.0
 */

interface TelemetryConfig1 {
    enableTelemetry?: boolean;
    metricConfigs?: WorkflowNodeMetricConfig[];
}

/**
 * Generated by orval 🍺
 * Do not edit manually.
 * api API
 * OpenAPI spec version: 1.0
 */
interface Trigger {
    type?: string;
}

/**
 * Generated by orval 🍺
 * Do not edit manually.
 * api API
 * OpenAPI spec version: 1.0
 */
type TransformerConfigContext = {
    [key: string]: unknown;
};

/**
 * Generated by orval 🍺
 * Do not edit manually.
 * api API
 * OpenAPI spec version: 1.0
 */
type TransformerConfigInputs = {
    [key: string]: unknown;
};

/**
 * Generated by orval 🍺
 * Do not edit manually.
 * api API
 * OpenAPI spec version: 1.0
 */
type TransformerConfigAdditional = {
    [key: string]: unknown;
};

/**
 * Generated by orval 🍺
 * Do not edit manually.
 * api API
 * OpenAPI spec version: 1.0
 */

interface TransformerConfig {
    /** @pattern \S */
    id: string;
    /** @pattern \S */
    type: string;
    title?: string;
    subTitle?: string;
    trigger?: Trigger;
    context?: TransformerConfigContext;
    inputs?: TransformerConfigInputs;
    index?: number;
    additional?: TransformerConfigAdditional;
    skip?: boolean;
    debug?: boolean;
    /** @pattern \S */
    fallbackMode: string;
    groupId?: string;
    inputSchema?: SchemaAndLayout;
    outputSchema?: Schema;
    errorSchema?: Schema;
    options?: NodeOptions;
    dirty?: boolean;
    enabled?: boolean;
    includeOriginalOutput?: boolean;
}

/**
 * Generated by orval 🍺
 * Do not edit manually.
 * api API
 * OpenAPI spec version: 1.0
 */
interface BulkheadConfig {
    enabled?: boolean;
    maxConcurrency?: string;
    maxWaitDuration?: string;
    maxWaitDurationUnit?: string;
    maxLeaseTime?: string;
    maxLeaseTimeUnit?: string;
}

/**
 * Generated by orval 🍺
 * Do not edit manually.
 * api API
 * OpenAPI spec version: 1.0
 */
interface TimeoutConfig {
    enabled?: boolean;
    duration?: string;
    unit?: string;
}

/**
 * Generated by orval 🍺
 * Do not edit manually.
 * api API
 * OpenAPI spec version: 1.0
 */

/**
 * Options for the Node
 */
interface NodeOptions {
    cacheConfig?: CacheConfig;
    retryConfig?: RetryConfig1;
    retryRetryableWorkConfig?: RetryConfig1;
    rateLimitConfig?: RateLimitConfig1;
    rateLimitConfigWrapper?: RateLimitConfigWrapper1;
    circuitBreakerConfig?: CircuitBreakerConfiguration;
    businessHoursConfig?: BusinessHoursConfig;
    hookConfig?: HookConfig;
    logConfig?: LogConfig;
    telemetryConfig?: TelemetryConfig1;
    transformerConfig?: TransformerConfig;
    bulkheadConfig?: BulkheadConfig;
    timeoutConfig?: TimeoutConfig;
    stepError?: string;
    disableLogging?: boolean;
    enabledForReExecution?: boolean;
}

/**
 * Generated by orval 🍺
 * Do not edit manually.
 * api API
 * OpenAPI spec version: 1.0
 */
type ExecuteWorkflowNodeRequestTransformerParameters = {
    [key: string]: unknown;
};

/**
 * Generated by orval 🍺
 * Do not edit manually.
 * api API
 * OpenAPI spec version: 1.0
 */
type ExecuteWorkflowNodeRequestSessionVariables = {
    [key: string]: unknown;
};

/**
 * Generated by orval 🍺
 * Do not edit manually.
 * api API
 * OpenAPI spec version: 1.0
 */

interface ExecuteWorkflowNodeRequest {
    id?: string;
    context?: ExecuteWorkflowNodeRequestContext;
    inputs?: ExecuteWorkflowNodeRequestInputs;
    lookupRequests?: LookupRequest[];
    options?: NodeOptions;
    transformerParameters?: ExecuteWorkflowNodeRequestTransformerParameters;
    sessionVariables?: ExecuteWorkflowNodeRequestSessionVariables;
    runtimeType?: string;
    secureRuns?: boolean;
    debug?: boolean;
    debugSessionId?: string;
}

export type { ExecuteWorkflowNodeResponse as E, ExecuteWorkflowNodeRequest as a };
