import { Options, HTTPError } from 'ky';

type FetchArgs = {
    url: string;
    method: 'GET' | 'POST' | 'PUT' | 'DELETE' | 'PATCH';
    params?: NonNullable<unknown>;
    headers?: NonNullable<unknown>;
    data?: NonNullable<unknown>;
    rawBody?: BodyInit | null;
    responseType?: string;
    signal?: AbortSignal;
};
type LogoutArgs = {
    logoutMode?: 'soft' | 'hard';
    source: string;
};
type QueryMeta = {
    interfaceId?: string;
    apiDomain?: string;
    /**
     * this is used to determine if the interface is public or private
     * if true, the interface is public and the apis will be prefixed with /api-endpoint/external/...
     * if false, the interface is private and the apis will be prefixed with /api/...
     */
    isPublicInterface?: boolean;
    /**
     * this is used in matrix-native to logout the user when the active session is expired
     */
    logout?: (args: LogoutArgs) => Promise<void>;
    /**
     * this is used to determine if the page is public or private
     * if true, the page is public and the apis will be prefixed with /auth/...
     * if false, the page is private and the apis will be prefixed with /api/...
     *
     * note: the network hook composes this with `isUserLoggedIn` — a logged-in
     * visitor on a public page still hits /api/* so their session is honored.
     * setters can pass the raw page-public flag.
     */
    isPublicPage?: boolean;
    /**
     * true when the visitor has an authenticated session. injected at the
     * queryMeta root by each app's QueryProvider so the network hook can compose
     * with `isPublicPage` without sniffing cookies (the `_at` session cookie is
     * HttpOnly and not all login flows mirror it into a client-readable cookie).
     */
    isUserLoggedIn?: boolean;
    headers?: Record<string, string>;
    basePath?: string;
};
type FetchOptions = {
    cache?: RequestCache;
    credentials?: RequestInit['credentials'];
    /**
     * Streams the response body and reports download progress (forwarded to ky). `totalBytes` is 0
     * when the server omits content-length.
     */
    onDownloadProgress?: Options['onDownloadProgress'];
    /**
     * in some case we don't want to fetch the entire body, just require the headers
     * eg: want to check if the file exists, want to get the redirect url etc.
     * returnRawResponse will then return the response object instead of calling res.text() or res.json() which will consume the body
     */
    returnRawResponse?: boolean;
    /**
     * if true,  packages/network/src/utils/fetch/hooks/afterResponse/logout.ts
     * will set window.location.href to the redirect url
     * if false, the redirect will be handled by the browser
     * this is introcuces as we fetcgh csv files from the server and the server returns a redirect url
     * as  window.location.href is used to redirect files gets downloaded in the same tab
     */
    shouldRedirect?: boolean;
    debugParams?: Record<string, string | undefined>;
    headers?: Record<string, string>;
    meta?: Record<string, unknown> & QueryMeta & {
        disableProjectHeader?: boolean;
        disableInterfaceHeader?: boolean;
    };
};

declare enum UAError {
    UNMAPPED = -1,
    STALE_OBJECT = 5001,
    ASSET_NOT_FOUND = 5002,
    TRY_AGAIN = 5003,
    VALIDATION_ERROR = 5004,
    WORKFLOW_ERROR = 5005,
    RESOURCE_NOT_FOUND = 5006,
    MISSING_PROPERTY = 5007,
    USER_VISIBLE_ERROR = 5008,
    DUPLICATE_KEY_ERROR = 5010,
    FORBIDDEN = 5011
}
type ErrorPayload<T = Record<string, unknown>> = {
    errorId?: string;
    errorCode?: UAError;
    message?: string;
    errorMessage?: string;
} & T;

declare class UAFetchError<T = Record<string, unknown>> extends HTTPError<T> {
    payload: ErrorPayload<T> | undefined;
    status: number;
    statusText: string;
    url: string;
    reqHeaders: Record<string, unknown>;
    constructor({ request, response, options, message, payload, status, statusText, url, }: {
        request: HTTPError['request'];
        response: HTTPError['response'];
        options: HTTPError['options'];
        message: string;
        payload?: ErrorPayload<T>;
        url: string;
        status: number;
        statusText: string;
    });
}

declare const executeFetch: <T>(fetchArgs: FetchArgs, options?: FetchOptions) => Promise<T>;
type ErrorType<T> = UAFetchError<T>;

/**
 * Generated by orval 🍺
 * Do not edit manually.
 * api API
 * OpenAPI spec version: 1.0
 */
type Op = (typeof Op)[keyof typeof Op];
declare const Op: {
    readonly AND: "AND";
    readonly OR: "OR";
    readonly NOT: "NOT";
    readonly EQUAL: "EQUAL";
    readonly NOT_EQUAL: "NOT_EQUAL";
    readonly IN: "IN";
    readonly NOT_IN: "NOT_IN";
    readonly LT: "LT";
    readonly LTE: "LTE";
    readonly GT: "GT";
    readonly GTE: "GTE";
    readonly BETWEEN: "BETWEEN";
    readonly REGEX: "REGEX";
    readonly NOT_REGEX: "NOT_REGEX";
    readonly STARTS_WITH: "STARTS_WITH";
    readonly NOT_STARTS_WITH: "NOT_STARTS_WITH";
    readonly ENDS_WITH: "ENDS_WITH";
    readonly NOT_ENDS_WITH: "NOT_ENDS_WITH";
    readonly CONTAINS: "CONTAINS";
    readonly NOT_CONTAINS: "NOT_CONTAINS";
    readonly MIN_LENGTH: "MIN_LENGTH";
    readonly MAX_LENGTH: "MAX_LENGTH";
    readonly IREGEX: "IREGEX";
    readonly NOT_IREGEX: "NOT_IREGEX";
    readonly ICONTAINS: "ICONTAINS";
    readonly NOT_ICONTAINS: "NOT_ICONTAINS";
    readonly EXISTS: "EXISTS";
    readonly MISSING: "MISSING";
    readonly WITHIN: "WITHIN";
    readonly CONTEXTUAL: "CONTEXTUAL";
};

/**
 * Generated by orval 🍺
 * Do not edit manually.
 * api API
 * OpenAPI spec version: 1.0
 */
type FilterOptions = {
    [key: string]: unknown;
};

/**
 * Generated by orval 🍺
 * Do not edit manually.
 * api API
 * OpenAPI spec version: 1.0
 */
type FilterMetadata = {
    [key: string]: string;
};

/**
 * Generated by orval 🍺
 * Do not edit manually.
 * api API
 * OpenAPI spec version: 1.0
 */

interface Filter {
    field?: string;
    op?: Op;
    values?: unknown[];
    options?: FilterOptions;
    metadata?: FilterMetadata;
}

export { executeFetch as e };
export type { ErrorType as E, Filter as F };
