/**
 * Generated by orval 🍺
 * Do not edit manually.
 * api API
 * OpenAPI spec version: 1.0
 */
type PrincipalType = (typeof PrincipalType)[keyof typeof PrincipalType];
declare const PrincipalType: {
    readonly GLOBAL: "GLOBAL";
    readonly USER: "USER";
    readonly USER_GROUPS: "USER_GROUPS";
    readonly SPACE: "SPACE";
};

/**
 * Generated by orval 🍺
 * Do not edit manually.
 * api API
 * OpenAPI spec version: 1.0
 */

interface Grant {
    principalType?: PrincipalType;
    principalIds?: string[];
    permissions?: string[];
}

/**
 * Generated by orval 🍺
 * Do not edit manually.
 * api API
 * OpenAPI spec version: 1.0
 */

interface Grants {
    configs?: Grant[];
}

export type { Grants as G };
