import { F as Filter } from './filter-BBRpwKD3.js';

/**
 * Generated by orval 🍺
 * Do not edit manually.
 * api API
 * OpenAPI spec version: 1.0
 */
interface Cursor {
    next?: string;
    previous?: string;
}

/**
 * Generated by orval 🍺
 * Do not edit manually.
 * api API
 * OpenAPI spec version: 1.0
 */
type Order = (typeof Order)[keyof typeof Order];
declare const Order: {
    readonly ASC: "ASC";
    readonly DESC: "DESC";
};

/**
 * Generated by orval 🍺
 * Do not edit manually.
 * api API
 * OpenAPI spec version: 1.0
 */
type SortAdditional = {
    [key: string]: unknown;
};

/**
 * Generated by orval 🍺
 * Do not edit manually.
 * api API
 * OpenAPI spec version: 1.0
 */

interface Sort {
    field?: string;
    order?: Order;
    additional?: SortAdditional;
}

/**
 * Generated by orval 🍺
 * Do not edit manually.
 * api API
 * OpenAPI spec version: 1.0
 */
interface Page {
    offset?: number;
    limit?: number;
    cursor?: string;
    batchSize?: number;
}

/**
 * Generated by orval 🍺
 * Do not edit manually.
 * api API
 * OpenAPI spec version: 1.0
 */
type QueryAdditional = {
    [key: string]: unknown;
};

/**
 * Generated by orval 🍺
 * Do not edit manually.
 * api API
 * OpenAPI spec version: 1.0
 */

interface InnerHitsSpec {
    name?: string;
    size?: number;
    from?: number;
    sorts?: Sort[];
}

/**
 * Generated by orval 🍺
 * Do not edit manually.
 * api API
 * OpenAPI spec version: 1.0
 */

interface Collapse {
    field?: string;
    innerHits?: InnerHitsSpec;
    maxConcurrentGroupSearches?: number;
}

/**
 * Generated by orval 🍺
 * Do not edit manually.
 * api API
 * OpenAPI spec version: 1.0
 */

interface Query {
    filter?: Filter;
    sorts?: Sort[];
    page?: Page;
    includeTotalHits?: boolean;
    maxExecutionTimeInMillis?: number;
    additional?: QueryAdditional;
    excludeFields?: string[];
    collapse?: Collapse;
}

export type { Cursor as C, Page as P, Query as Q, Sort as S, Collapse as a };
