import { F as Filter } from './filter-BBRpwKD3.js';

/**
 * Generated by orval 🍺
 * Do not edit manually.
 * api API
 * OpenAPI spec version: 1.0
 */
type CompoundOps = (typeof CompoundOps)[keyof typeof CompoundOps];
declare const CompoundOps: {
    readonly AND: "AND";
    readonly OR: "OR";
};

/**
 * Generated by orval 🍺
 * Do not edit manually.
 * api API
 * OpenAPI spec version: 1.0
 */
type SimpleOps = (typeof SimpleOps)[keyof typeof SimpleOps];
declare const SimpleOps: {
    readonly EQUAL: "EQUAL";
    readonly NOT_EQUAL: "NOT_EQUAL";
    readonly CONTAINS: "CONTAINS";
    readonly IN: "IN";
    readonly NOT_IN: "NOT_IN";
    readonly NOT_CONTAINS: "NOT_CONTAINS";
    readonly ICONTAINS: "ICONTAINS";
    readonly NOT_ICONTAINS: "NOT_ICONTAINS";
    readonly REGEX: "REGEX";
    readonly NOT_REGEX: "NOT_REGEX";
    readonly IREGEX: "IREGEX";
    readonly NOT_IREGEX: "NOT_IREGEX";
    readonly STARTS_WITH: "STARTS_WITH";
    readonly NOT_STARTS_WITH: "NOT_STARTS_WITH";
    readonly ENDS_WITH: "ENDS_WITH";
    readonly NOT_ENDS_WITH: "NOT_ENDS_WITH";
    readonly MIN_LENGTH: "MIN_LENGTH";
    readonly MAX_LENGTH: "MAX_LENGTH";
    readonly EXISTS: "EXISTS";
    readonly MISSING: "MISSING";
    readonly LT: "LT";
    readonly LTE: "LTE";
    readonly GT: "GT";
    readonly GTE: "GTE";
    readonly BETWEEN: "BETWEEN";
    readonly WITHIN: "WITHIN";
};

/**
 * Generated by orval 🍺
 * Do not edit manually.
 * api API
 * OpenAPI spec version: 1.0
 */

interface ResolvedFilter {
    name?: string;
    filter?: Filter;
}

/**
 * Generated by orval 🍺
 * Do not edit manually.
 * api API
 * OpenAPI spec version: 1.0
 */
type SchemaAndLayoutType = (typeof SchemaAndLayoutType)[keyof typeof SchemaAndLayoutType];
declare const SchemaAndLayoutType: {
    readonly SCHEMA_AND_LAYOUT: "SCHEMA_AND_LAYOUT";
};

/**
 * Generated by orval 🍺
 * Do not edit manually.
 * api API
 * OpenAPI spec version: 1.0
 */
type SchemaAndLayoutSchema = {
    [key: string]: unknown;
};

/**
 * Generated by orval 🍺
 * Do not edit manually.
 * api API
 * OpenAPI spec version: 1.0
 */
type SchemaAndLayoutMetadata = {
    [key: string]: unknown;
};

/**
 * Generated by orval 🍺
 * Do not edit manually.
 * api API
 * OpenAPI spec version: 1.0
 */
type SchemaAndLayoutLayout = {
    [key: string]: unknown;
};

/**
 * Generated by orval 🍺
 * Do not edit manually.
 * api API
 * OpenAPI spec version: 1.0
 */

interface SchemaAndLayout {
    type: SchemaAndLayoutType;
    schema?: SchemaAndLayoutSchema;
    dynamic?: boolean;
    metadata?: SchemaAndLayoutMetadata;
    layout?: SchemaAndLayoutLayout;
}

/**
 * Generated by orval 🍺
 * Do not edit manually.
 * api API
 * OpenAPI spec version: 1.0
 */
type SchemaTypeProperty = (typeof SchemaTypeProperty)[keyof typeof SchemaTypeProperty];
declare const SchemaTypeProperty: {
    readonly SCHEMA: "SCHEMA";
};

/**
 * Generated by orval 🍺
 * Do not edit manually.
 * api API
 * OpenAPI spec version: 1.0
 */
type SchemaSchema = {
    [key: string]: unknown;
};

/**
 * Generated by orval 🍺
 * Do not edit manually.
 * api API
 * OpenAPI spec version: 1.0
 */
type SchemaMetadata = {
    [key: string]: unknown;
};

/**
 * Generated by orval 🍺
 * Do not edit manually.
 * api API
 * OpenAPI spec version: 1.0
 */

interface Schema {
    type: SchemaTypeProperty;
    schema?: SchemaSchema;
    dynamic?: boolean;
    metadata?: SchemaMetadata;
}

export { CompoundOps as C, SimpleOps as S };
export type { ResolvedFilter as R, SchemaAndLayout as a, Schema as b };
