import { E as ExecuteWorkflowNodeResponse, a as ExecuteWorkflowNodeRequest } from '../executeWorkflowNodeRequest-C8zxXSRc.js';
import * as _tanstack_react_query from '@tanstack/react-query';
import { UseMutationOptions, UseQueryOptions, DataTag, QueryKey, QueryClient, UseMutationResult, DefinedInitialDataOptions, DefinedUseQueryResult, UndefinedInitialDataOptions, UseQueryResult } from '@tanstack/react-query';
import * as _tanstack_query_core from '@tanstack/query-core';
import { C as CurrentUserDetails } from '../currentUserDetails-D5hr8tW-.js';
import { G as Grants } from '../grants-Bl8lIEzI.js';
import { F as Filter, E as ErrorType, e as executeFetch } from '../filter-BBRpwKD3.js';
import { C as Cursor, Q as Query } from '../query-C4wXz6Iu.js';
import '../schema-CHL6CK9Q.js';
import 'ky';

/**
 * Generated by orval 🍺
 * Do not edit manually.
 * api API
 * OpenAPI spec version: 1.0
 */
type IdentityProviderCustomProperties = {
    [key: string]: unknown;
};

/**
 * Generated by orval 🍺
 * Do not edit manually.
 * api API
 * OpenAPI spec version: 1.0
 */
interface MFARateLimitPolicy {
    activityDuration?: number;
    threshold?: number;
    lockDuration?: number;
}

/**
 * Generated by orval 🍺
 * Do not edit manually.
 * api API
 * OpenAPI spec version: 1.0
 */
type MFAConfigCustomMessages = {
    [key: string]: string;
};

/**
 * Generated by orval 🍺
 * Do not edit manually.
 * api API
 * OpenAPI spec version: 1.0
 */

interface MFAConfig {
    type?: string;
    workflowId?: string;
    verificationWorkflowId?: string;
    numberOfRetries?: number;
    triggerLimitPolicy?: MFARateLimitPolicy;
    reTriggerLimitPolicy?: MFARateLimitPolicy;
    verificationLimitPolicy?: MFARateLimitPolicy;
    failedAttemptsLimitPolicy?: MFARateLimitPolicy;
    customMessages?: MFAConfigCustomMessages;
}

/**
 * Generated by orval 🍺
 * Do not edit manually.
 * api API
 * OpenAPI spec version: 1.0
 */
interface SecurityConfig {
    key?: string;
    algorithm?: string;
    scheme?: string;
}

/**
 * Generated by orval 🍺
 * Do not edit manually.
 * api API
 * OpenAPI spec version: 1.0
 */
interface PostLoginConfig {
    workflowId?: string;
}

/**
 * Generated by orval 🍺
 * Do not edit manually.
 * api API
 * OpenAPI spec version: 1.0
 */
interface PostLogoutConfig {
    workflowId?: string;
}

/**
 * Generated by orval 🍺
 * Do not edit manually.
 * api API
 * OpenAPI spec version: 1.0
 */
type IdentityProviderSpecificConfigSessionAttributesPath = {
    [key: string]: string;
};

/**
 * Generated by orval 🍺
 * Do not edit manually.
 * api API
 * OpenAPI spec version: 1.0
 */

interface IdentityProviderSpecificConfig {
    _type?: string;
    mfaConfig?: MFAConfig;
    resetPasswordMfaConfig?: MFAConfig;
    resetMPINMfaConfig?: MFAConfig;
    updateUserMfaConfig?: MFAConfig;
    securityConfig?: SecurityConfig;
    postLoginConfig?: PostLoginConfig;
    postLogoutConfig?: PostLogoutConfig;
    sessionAttributesPath?: IdentityProviderSpecificConfigSessionAttributesPath;
    loginFilter?: Filter;
    jitFilter?: Filter;
    jitFilterStr?: string;
    loginFilterStr?: string;
    mappedCustomPropertyKeys?: string[];
}

/**
 * Generated by orval 🍺
 * Do not edit manually.
 * api API
 * OpenAPI spec version: 1.0
 */
type IDPUIConfigButton = {
    [key: string]: unknown;
};

/**
 * Generated by orval 🍺
 * Do not edit manually.
 * api API
 * OpenAPI spec version: 1.0
 */
type IDPUIConfigForm = {
    [key: string]: unknown;
};

/**
 * Generated by orval 🍺
 * Do not edit manually.
 * api API
 * OpenAPI spec version: 1.0
 */

interface IDPUIConfig {
    type?: string;
    button?: IDPUIConfigButton;
    form?: IDPUIConfigForm;
    securityConfig?: SecurityConfig;
}

/**
 * Generated by orval 🍺
 * Do not edit manually.
 * api API
 * OpenAPI spec version: 1.0
 */

interface IdentityProvider {
    lcName?: string;
    version?: number;
    createdTime?: number;
    modifiedTime?: number;
    lastPlatformUpdateOn?: number;
    lastPlatformUpdateBy?: number;
    ownerUserId?: number;
    lastModifiedBy?: number;
    deleted?: boolean;
    grants?: Grants;
    flattenedGrants?: string[];
    projectId?: number;
    spaceId?: string;
    tags?: string[];
    customProperties?: IdentityProviderCustomProperties;
    id?: string;
    name?: string;
    type?: string;
    applicationId?: string;
    providerConfig?: IdentityProviderSpecificConfig;
    uiConfig?: IDPUIConfig;
    autoCreateUser?: boolean;
    defaultLoginStateId?: string;
    showRemainingLoginAttempts?: boolean;
    allowedMaxLoginFailures?: number;
    failureAttemptResetDuration?: number;
    sessionExpiryTime?: number;
    keepExternalSession?: boolean;
    excludeRedirectUrlFromResponse?: boolean;
    standard?: boolean;
    active?: boolean;
    external?: boolean;
    configProvider?: string;
    iconUrl?: string;
    restrictMultipleSessions?: boolean;
    userCustomAttributesSync?: boolean;
    sessionIdField?: string;
    partitionDisabled?: boolean;
    enableRefreshToken?: boolean;
    singleTabSession?: boolean;
    refreshTokenExpiryTime?: number;
    userLockoutDuration?: number;
    externalSessionExpiryTime?: number;
    externalSessionExpiryTimeUnit?: string;
    allowPackagedSession?: boolean;
    createTemporarySession?: boolean;
    allowedRequestOrigins?: string[];
    requestOriginatedHeaderKey?: string;
    skipHTTPSchemesForRequestOrigins?: string[];
}

/**
 * Generated by orval 🍺
 * Do not edit manually.
 * api API
 * OpenAPI spec version: 1.0
 */
type HitsIdentityProviderInnerHitsItemItem = {
    [key: string]: unknown;
};

/**
 * Generated by orval 🍺
 * Do not edit manually.
 * api API
 * OpenAPI spec version: 1.0
 */

type HitsIdentityProviderInnerHitsItem = {
    [key: string]: HitsIdentityProviderInnerHitsItemItem[];
};

/**
 * Generated by orval 🍺
 * Do not edit manually.
 * api API
 * OpenAPI spec version: 1.0
 */

interface HitsIdentityProvider {
    objects?: IdentityProvider[];
    cursor?: Cursor;
    hasMore?: boolean;
    totalHits?: number;
    innerHits?: HitsIdentityProviderInnerHitsItem[];
    type?: string;
}

type AuthNodeResponse<TResponse> = Omit<ExecuteWorkflowNodeResponse, 'response'> & {
    response: TResponse;
};
declare function sendForgotPasswordEmail(username: string, signal?: AbortSignal, meta?: Record<string, unknown>): Promise<AuthNodeResponse<unknown>>;

/**
 * Generated by orval 🍺
 * Do not edit manually.
 * api API
 * OpenAPI spec version: 1.0
 */
interface SAMLMetadataImportRequest {
    source?: string;
}

/**
 * Generated by orval 🍺
 * Do not edit manually.
 * api API
 * OpenAPI spec version: 1.0
 */
interface SAMLMetadataResponse {
    idpEntityId?: string;
    idpSsoUrl?: string;
    idpCertificate?: string;
    spAcsBinding?: string;
}

type SecondParameter$1<T extends (...args: never) => unknown> = Parameters<T>[1];
/**
 * @summary Fetch Identity Providers
 */
declare const fetchIdentityProviders: (query: Query, options?: SecondParameter$1<typeof executeFetch>, signal?: AbortSignal) => Promise<HitsIdentityProvider>;
declare const getFetchIdentityProvidersQueryKey: (query?: Query) => readonly ["/api/identity-provider", Query | undefined];
declare const getFetchIdentityProvidersQueryOptions: <TData = Awaited<ReturnType<typeof fetchIdentityProviders>>, TError = ErrorType<unknown>>(query: Query, options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof fetchIdentityProviders>>, TError, TData>>;
    request?: SecondParameter$1<typeof executeFetch>;
}) => UseQueryOptions<Awaited<ReturnType<typeof fetchIdentityProviders>>, TError, TData> & {
    queryKey: DataTag<QueryKey, TData, TError>;
};
type FetchIdentityProvidersQueryResult = NonNullable<Awaited<ReturnType<typeof fetchIdentityProviders>>>;
type FetchIdentityProvidersQueryError = ErrorType<unknown>;
declare function useFetchIdentityProviders<TData = Awaited<ReturnType<typeof fetchIdentityProviders>>, TError = ErrorType<unknown>>(query: Query, options: {
    query: Partial<UseQueryOptions<Awaited<ReturnType<typeof fetchIdentityProviders>>, TError, TData>> & Pick<DefinedInitialDataOptions<Awaited<ReturnType<typeof fetchIdentityProviders>>, TError, Awaited<ReturnType<typeof fetchIdentityProviders>>>, "initialData">;
    request?: SecondParameter$1<typeof executeFetch>;
}, queryClient?: QueryClient): DefinedUseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
};
declare function useFetchIdentityProviders<TData = Awaited<ReturnType<typeof fetchIdentityProviders>>, TError = ErrorType<unknown>>(query: Query, options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof fetchIdentityProviders>>, TError, TData>> & Pick<UndefinedInitialDataOptions<Awaited<ReturnType<typeof fetchIdentityProviders>>, TError, Awaited<ReturnType<typeof fetchIdentityProviders>>>, "initialData">;
    request?: SecondParameter$1<typeof executeFetch>;
}, queryClient?: QueryClient): UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
};
declare function useFetchIdentityProviders<TData = Awaited<ReturnType<typeof fetchIdentityProviders>>, TError = ErrorType<unknown>>(query: Query, options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof fetchIdentityProviders>>, TError, TData>>;
    request?: SecondParameter$1<typeof executeFetch>;
}, queryClient?: QueryClient): UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Fetch Identity Providers
 */
declare const prefetchFetchIdentityProviders: <TData = Awaited<ReturnType<typeof fetchIdentityProviders>>, TError = ErrorType<unknown>>(queryClient: QueryClient, query: Query, options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof fetchIdentityProviders>>, TError, TData>>;
    request?: SecondParameter$1<typeof executeFetch>;
}) => Promise<QueryClient>;
/**
 * @summary Create Or Update Identity Provider
 */
declare const createOrUpdateIdentityProvider: (identityProvider: IdentityProvider, options?: SecondParameter$1<typeof executeFetch>, signal?: AbortSignal) => Promise<IdentityProvider>;
declare const getCreateOrUpdateIdentityProviderMutationOptions: <TError = ErrorType<unknown>, TContext = unknown>(options?: {
    mutation?: UseMutationOptions<Awaited<ReturnType<typeof createOrUpdateIdentityProvider>>, TError, {
        data: IdentityProvider;
    }, TContext>;
    request?: SecondParameter$1<typeof executeFetch>;
}) => UseMutationOptions<Awaited<ReturnType<typeof createOrUpdateIdentityProvider>>, TError, {
    data: IdentityProvider;
}, TContext>;
type CreateOrUpdateIdentityProviderMutationResult = NonNullable<Awaited<ReturnType<typeof createOrUpdateIdentityProvider>>>;
type CreateOrUpdateIdentityProviderMutationBody = IdentityProvider;
type CreateOrUpdateIdentityProviderMutationError = ErrorType<unknown>;
/**
 * @summary Create Or Update Identity Provider
 */
declare const useCreateOrUpdateIdentityProvider: <TError = ErrorType<unknown>, TContext = unknown>(options?: {
    mutation?: UseMutationOptions<Awaited<ReturnType<typeof createOrUpdateIdentityProvider>>, TError, {
        data: IdentityProvider;
    }, TContext>;
    request?: SecondParameter$1<typeof executeFetch>;
}, queryClient?: QueryClient) => UseMutationResult<Awaited<ReturnType<typeof createOrUpdateIdentityProvider>>, TError, {
    data: IdentityProvider;
}, TContext>;
/**
 * @summary Delete Identity Provider
 */
declare const deleteIdentityProvider: (identityProviderId: string, options?: SecondParameter$1<typeof executeFetch>, signal?: AbortSignal) => Promise<void>;
declare const getDeleteIdentityProviderMutationOptions: <TError = ErrorType<unknown>, TContext = unknown>(options?: {
    mutation?: UseMutationOptions<Awaited<ReturnType<typeof deleteIdentityProvider>>, TError, {
        identityProviderId: string;
    }, TContext>;
    request?: SecondParameter$1<typeof executeFetch>;
}) => UseMutationOptions<Awaited<ReturnType<typeof deleteIdentityProvider>>, TError, {
    identityProviderId: string;
}, TContext>;
type DeleteIdentityProviderMutationResult = NonNullable<Awaited<ReturnType<typeof deleteIdentityProvider>>>;
type DeleteIdentityProviderMutationError = ErrorType<unknown>;
/**
 * @summary Delete Identity Provider
 */
declare const useDeleteIdentityProvider: <TError = ErrorType<unknown>, TContext = unknown>(options?: {
    mutation?: UseMutationOptions<Awaited<ReturnType<typeof deleteIdentityProvider>>, TError, {
        identityProviderId: string;
    }, TContext>;
    request?: SecondParameter$1<typeof executeFetch>;
}, queryClient?: QueryClient) => UseMutationResult<Awaited<ReturnType<typeof deleteIdentityProvider>>, TError, {
    identityProviderId: string;
}, TContext>;
/**
 * @summary Get Identity Providers
 */
declare const getIdentityProviders: (query: Query, options?: SecondParameter$1<typeof executeFetch>, signal?: AbortSignal) => Promise<HitsIdentityProvider>;
declare const getGetIdentityProvidersQueryKey: (query?: Query) => readonly ["/api/identity-provider/fetch-identity-providers", Query | undefined];
declare const getGetIdentityProvidersQueryOptions: <TData = Awaited<ReturnType<typeof getIdentityProviders>>, TError = ErrorType<unknown>>(query: Query, options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getIdentityProviders>>, TError, TData>>;
    request?: SecondParameter$1<typeof executeFetch>;
}) => UseQueryOptions<Awaited<ReturnType<typeof getIdentityProviders>>, TError, TData> & {
    queryKey: DataTag<QueryKey, TData, TError>;
};
type GetIdentityProvidersQueryResult = NonNullable<Awaited<ReturnType<typeof getIdentityProviders>>>;
type GetIdentityProvidersQueryError = ErrorType<unknown>;
declare function useGetIdentityProviders<TData = Awaited<ReturnType<typeof getIdentityProviders>>, TError = ErrorType<unknown>>(query: Query, options: {
    query: Partial<UseQueryOptions<Awaited<ReturnType<typeof getIdentityProviders>>, TError, TData>> & Pick<DefinedInitialDataOptions<Awaited<ReturnType<typeof getIdentityProviders>>, TError, Awaited<ReturnType<typeof getIdentityProviders>>>, "initialData">;
    request?: SecondParameter$1<typeof executeFetch>;
}, queryClient?: QueryClient): DefinedUseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
};
declare function useGetIdentityProviders<TData = Awaited<ReturnType<typeof getIdentityProviders>>, TError = ErrorType<unknown>>(query: Query, options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getIdentityProviders>>, TError, TData>> & Pick<UndefinedInitialDataOptions<Awaited<ReturnType<typeof getIdentityProviders>>, TError, Awaited<ReturnType<typeof getIdentityProviders>>>, "initialData">;
    request?: SecondParameter$1<typeof executeFetch>;
}, queryClient?: QueryClient): UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
};
declare function useGetIdentityProviders<TData = Awaited<ReturnType<typeof getIdentityProviders>>, TError = ErrorType<unknown>>(query: Query, options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getIdentityProviders>>, TError, TData>>;
    request?: SecondParameter$1<typeof executeFetch>;
}, queryClient?: QueryClient): UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Get Identity Providers
 */
declare const prefetchGetIdentityProviders: <TData = Awaited<ReturnType<typeof getIdentityProviders>>, TError = ErrorType<unknown>>(queryClient: QueryClient, query: Query, options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getIdentityProviders>>, TError, TData>>;
    request?: SecondParameter$1<typeof executeFetch>;
}) => Promise<QueryClient>;
/**
 * @summary Import SAML Metadata
 */
declare const importSAMLMetadata: (sAMLMetadataImportRequest: SAMLMetadataImportRequest, options?: SecondParameter$1<typeof executeFetch>, signal?: AbortSignal) => Promise<SAMLMetadataResponse>;
declare const getImportSAMLMetadataMutationOptions: <TError = ErrorType<unknown>, TContext = unknown>(options?: {
    mutation?: UseMutationOptions<Awaited<ReturnType<typeof importSAMLMetadata>>, TError, {
        data: SAMLMetadataImportRequest;
    }, TContext>;
    request?: SecondParameter$1<typeof executeFetch>;
}) => UseMutationOptions<Awaited<ReturnType<typeof importSAMLMetadata>>, TError, {
    data: SAMLMetadataImportRequest;
}, TContext>;
type ImportSAMLMetadataMutationResult = NonNullable<Awaited<ReturnType<typeof importSAMLMetadata>>>;
type ImportSAMLMetadataMutationBody = SAMLMetadataImportRequest;
type ImportSAMLMetadataMutationError = ErrorType<unknown>;
/**
 * @summary Import SAML Metadata
 */
declare const useImportSAMLMetadata: <TError = ErrorType<unknown>, TContext = unknown>(options?: {
    mutation?: UseMutationOptions<Awaited<ReturnType<typeof importSAMLMetadata>>, TError, {
        data: SAMLMetadataImportRequest;
    }, TContext>;
    request?: SecondParameter$1<typeof executeFetch>;
}, queryClient?: QueryClient) => UseMutationResult<Awaited<ReturnType<typeof importSAMLMetadata>>, TError, {
    data: SAMLMetadataImportRequest;
}, TContext>;
/**
 * @summary Toggle Active
 */
declare const toggleActive: (identityProviderId: string, options?: SecondParameter$1<typeof executeFetch>, signal?: AbortSignal) => Promise<void>;
declare const getToggleActiveMutationOptions: <TError = ErrorType<unknown>, TContext = unknown>(options?: {
    mutation?: UseMutationOptions<Awaited<ReturnType<typeof toggleActive>>, TError, {
        identityProviderId: string;
    }, TContext>;
    request?: SecondParameter$1<typeof executeFetch>;
}) => UseMutationOptions<Awaited<ReturnType<typeof toggleActive>>, TError, {
    identityProviderId: string;
}, TContext>;
type ToggleActiveMutationResult = NonNullable<Awaited<ReturnType<typeof toggleActive>>>;
type ToggleActiveMutationError = ErrorType<unknown>;
/**
 * @summary Toggle Active
 */
declare const useToggleActive: <TError = ErrorType<unknown>, TContext = unknown>(options?: {
    mutation?: UseMutationOptions<Awaited<ReturnType<typeof toggleActive>>, TError, {
        identityProviderId: string;
    }, TContext>;
    request?: SecondParameter$1<typeof executeFetch>;
}, queryClient?: QueryClient) => UseMutationResult<Awaited<ReturnType<typeof toggleActive>>, TError, {
    identityProviderId: string;
}, TContext>;
/**
 * @summary Get Identity Provider
 */
declare const findIdentityProviderById: (identityProviderId: string, options?: SecondParameter$1<typeof executeFetch>, signal?: AbortSignal) => Promise<IdentityProvider>;
declare const getFindIdentityProviderByIdQueryKey: (identityProviderId?: string) => readonly [`/api/identity-provider/${string}`];
declare const getFindIdentityProviderByIdQueryOptions: <TData = Awaited<ReturnType<typeof findIdentityProviderById>>, TError = ErrorType<unknown>>(identityProviderId: string, options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof findIdentityProviderById>>, TError, TData>>;
    request?: SecondParameter$1<typeof executeFetch>;
}) => UseQueryOptions<Awaited<ReturnType<typeof findIdentityProviderById>>, TError, TData> & {
    queryKey: DataTag<QueryKey, TData, TError>;
};
type FindIdentityProviderByIdQueryResult = NonNullable<Awaited<ReturnType<typeof findIdentityProviderById>>>;
type FindIdentityProviderByIdQueryError = ErrorType<unknown>;
declare function useFindIdentityProviderById<TData = Awaited<ReturnType<typeof findIdentityProviderById>>, TError = ErrorType<unknown>>(identityProviderId: string, options: {
    query: Partial<UseQueryOptions<Awaited<ReturnType<typeof findIdentityProviderById>>, TError, TData>> & Pick<DefinedInitialDataOptions<Awaited<ReturnType<typeof findIdentityProviderById>>, TError, Awaited<ReturnType<typeof findIdentityProviderById>>>, "initialData">;
    request?: SecondParameter$1<typeof executeFetch>;
}, queryClient?: QueryClient): DefinedUseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
};
declare function useFindIdentityProviderById<TData = Awaited<ReturnType<typeof findIdentityProviderById>>, TError = ErrorType<unknown>>(identityProviderId: string, options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof findIdentityProviderById>>, TError, TData>> & Pick<UndefinedInitialDataOptions<Awaited<ReturnType<typeof findIdentityProviderById>>, TError, Awaited<ReturnType<typeof findIdentityProviderById>>>, "initialData">;
    request?: SecondParameter$1<typeof executeFetch>;
}, queryClient?: QueryClient): UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
};
declare function useFindIdentityProviderById<TData = Awaited<ReturnType<typeof findIdentityProviderById>>, TError = ErrorType<unknown>>(identityProviderId: string, options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof findIdentityProviderById>>, TError, TData>>;
    request?: SecondParameter$1<typeof executeFetch>;
}, queryClient?: QueryClient): UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Get Identity Provider
 */
declare const prefetchFindIdentityProviderById: <TData = Awaited<ReturnType<typeof findIdentityProviderById>>, TError = ErrorType<unknown>>(queryClient: QueryClient, identityProviderId: string, options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof findIdentityProviderById>>, TError, TData>>;
    request?: SecondParameter$1<typeof executeFetch>;
}) => Promise<QueryClient>;

/**
 * Generated by orval 🍺
 * Do not edit manually.
 * api API
 * OpenAPI spec version: 1.0
 */
interface CreateApplicationSessionForUserRequest {
    userId?: string;
}

/**
 * Generated by orval 🍺
 * Do not edit manually.
 * api API
 * OpenAPI spec version: 1.0
 */
interface DeleteApplicationSessionForUserRequest {
    sessionId?: string;
    userId?: string;
}

/**
 * Generated by orval 🍺
 * Do not edit manually.
 * api API
 * OpenAPI spec version: 1.0
 */
type RedirectToApplicationSessionParams = {
    returnTo?: string;
};

/**
 * Generated by orval 🍺
 * Do not edit manually.
 * api API
 * OpenAPI spec version: 1.0
 */
interface SessionResponse {
    sessionId?: string;
    domain?: string;
}

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];
/**
 * @summary Redirect To Application Session
 */
declare const redirectToApplicationSession: (applicationId: string, params?: RedirectToApplicationSessionParams, options?: SecondParameter<typeof executeFetch>, signal?: AbortSignal) => Promise<unknown>;
declare const getRedirectToApplicationSessionQueryKey: (applicationId?: string, params?: RedirectToApplicationSessionParams) => readonly [`/api/session/application-session-redirect/${string}`, ...RedirectToApplicationSessionParams[]];
declare const getRedirectToApplicationSessionQueryOptions: <TData = Awaited<ReturnType<typeof redirectToApplicationSession>>, TError = ErrorType<unknown>>(applicationId: string, params?: RedirectToApplicationSessionParams, options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof redirectToApplicationSession>>, TError, TData>>;
    request?: SecondParameter<typeof executeFetch>;
}) => UseQueryOptions<Awaited<ReturnType<typeof redirectToApplicationSession>>, TError, TData> & {
    queryKey: DataTag<QueryKey, TData, TError>;
};
type RedirectToApplicationSessionQueryResult = NonNullable<Awaited<ReturnType<typeof redirectToApplicationSession>>>;
type RedirectToApplicationSessionQueryError = ErrorType<unknown>;
declare function useRedirectToApplicationSession<TData = Awaited<ReturnType<typeof redirectToApplicationSession>>, TError = ErrorType<unknown>>(applicationId: string, params: undefined | RedirectToApplicationSessionParams, options: {
    query: Partial<UseQueryOptions<Awaited<ReturnType<typeof redirectToApplicationSession>>, TError, TData>> & Pick<DefinedInitialDataOptions<Awaited<ReturnType<typeof redirectToApplicationSession>>, TError, Awaited<ReturnType<typeof redirectToApplicationSession>>>, "initialData">;
    request?: SecondParameter<typeof executeFetch>;
}, queryClient?: QueryClient): DefinedUseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
};
declare function useRedirectToApplicationSession<TData = Awaited<ReturnType<typeof redirectToApplicationSession>>, TError = ErrorType<unknown>>(applicationId: string, params?: RedirectToApplicationSessionParams, options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof redirectToApplicationSession>>, TError, TData>> & Pick<UndefinedInitialDataOptions<Awaited<ReturnType<typeof redirectToApplicationSession>>, TError, Awaited<ReturnType<typeof redirectToApplicationSession>>>, "initialData">;
    request?: SecondParameter<typeof executeFetch>;
}, queryClient?: QueryClient): UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
};
declare function useRedirectToApplicationSession<TData = Awaited<ReturnType<typeof redirectToApplicationSession>>, TError = ErrorType<unknown>>(applicationId: string, params?: RedirectToApplicationSessionParams, options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof redirectToApplicationSession>>, TError, TData>>;
    request?: SecondParameter<typeof executeFetch>;
}, queryClient?: QueryClient): UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Redirect To Application Session
 */
declare const prefetchRedirectToApplicationSession: <TData = Awaited<ReturnType<typeof redirectToApplicationSession>>, TError = ErrorType<unknown>>(queryClient: QueryClient, applicationId: string, params?: RedirectToApplicationSessionParams, options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof redirectToApplicationSession>>, TError, TData>>;
    request?: SecondParameter<typeof executeFetch>;
}) => Promise<QueryClient>;
/**
 * @summary Create Application Session For User
 */
declare const createApplicationSessionForUser: (createApplicationSessionForUserRequest: CreateApplicationSessionForUserRequest, options?: SecondParameter<typeof executeFetch>, signal?: AbortSignal) => Promise<SessionResponse>;
declare const getCreateApplicationSessionForUserMutationOptions: <TError = ErrorType<unknown>, TContext = unknown>(options?: {
    mutation?: UseMutationOptions<Awaited<ReturnType<typeof createApplicationSessionForUser>>, TError, {
        data: CreateApplicationSessionForUserRequest;
    }, TContext>;
    request?: SecondParameter<typeof executeFetch>;
}) => UseMutationOptions<Awaited<ReturnType<typeof createApplicationSessionForUser>>, TError, {
    data: CreateApplicationSessionForUserRequest;
}, TContext>;
type CreateApplicationSessionForUserMutationResult = NonNullable<Awaited<ReturnType<typeof createApplicationSessionForUser>>>;
type CreateApplicationSessionForUserMutationBody = CreateApplicationSessionForUserRequest;
type CreateApplicationSessionForUserMutationError = ErrorType<unknown>;
/**
 * @summary Create Application Session For User
 */
declare const useCreateApplicationSessionForUser: <TError = ErrorType<unknown>, TContext = unknown>(options?: {
    mutation?: UseMutationOptions<Awaited<ReturnType<typeof createApplicationSessionForUser>>, TError, {
        data: CreateApplicationSessionForUserRequest;
    }, TContext>;
    request?: SecondParameter<typeof executeFetch>;
}, queryClient?: QueryClient) => UseMutationResult<Awaited<ReturnType<typeof createApplicationSessionForUser>>, TError, {
    data: CreateApplicationSessionForUserRequest;
}, TContext>;
/**
 * @summary Create Application Session
 */
declare const createApplicationSession: (applicationId: string, options?: SecondParameter<typeof executeFetch>, signal?: AbortSignal) => Promise<SessionResponse>;
declare const getCreateApplicationSessionMutationOptions: <TError = ErrorType<unknown>, TContext = unknown>(options?: {
    mutation?: UseMutationOptions<Awaited<ReturnType<typeof createApplicationSession>>, TError, {
        applicationId: string;
    }, TContext>;
    request?: SecondParameter<typeof executeFetch>;
}) => UseMutationOptions<Awaited<ReturnType<typeof createApplicationSession>>, TError, {
    applicationId: string;
}, TContext>;
type CreateApplicationSessionMutationResult = NonNullable<Awaited<ReturnType<typeof createApplicationSession>>>;
type CreateApplicationSessionMutationError = ErrorType<unknown>;
/**
 * @summary Create Application Session
 */
declare const useCreateApplicationSession: <TError = ErrorType<unknown>, TContext = unknown>(options?: {
    mutation?: UseMutationOptions<Awaited<ReturnType<typeof createApplicationSession>>, TError, {
        applicationId: string;
    }, TContext>;
    request?: SecondParameter<typeof executeFetch>;
}, queryClient?: QueryClient) => UseMutationResult<Awaited<ReturnType<typeof createApplicationSession>>, TError, {
    applicationId: string;
}, TContext>;
/**
 * @summary Create Platform Session
 */
declare const createPlatformSession: (options?: SecondParameter<typeof executeFetch>, signal?: AbortSignal) => Promise<SessionResponse>;
declare const getCreatePlatformSessionMutationOptions: <TError = ErrorType<unknown>, TContext = unknown>(options?: {
    mutation?: UseMutationOptions<Awaited<ReturnType<typeof createPlatformSession>>, TError, void, TContext>;
    request?: SecondParameter<typeof executeFetch>;
}) => UseMutationOptions<Awaited<ReturnType<typeof createPlatformSession>>, TError, void, TContext>;
type CreatePlatformSessionMutationResult = NonNullable<Awaited<ReturnType<typeof createPlatformSession>>>;
type CreatePlatformSessionMutationError = ErrorType<unknown>;
/**
 * @summary Create Platform Session
 */
declare const useCreatePlatformSession: <TError = ErrorType<unknown>, TContext = unknown>(options?: {
    mutation?: UseMutationOptions<Awaited<ReturnType<typeof createPlatformSession>>, TError, void, TContext>;
    request?: SecondParameter<typeof executeFetch>;
}, queryClient?: QueryClient) => UseMutationResult<Awaited<ReturnType<typeof createPlatformSession>>, TError, void, TContext>;
/**
 * @summary Delete Application Session For User
 */
declare const deleteApplicationSessionForUser: (deleteApplicationSessionForUserRequest: DeleteApplicationSessionForUserRequest, options?: SecondParameter<typeof executeFetch>, signal?: AbortSignal) => Promise<void>;
declare const getDeleteApplicationSessionForUserMutationOptions: <TError = ErrorType<unknown>, TContext = unknown>(options?: {
    mutation?: UseMutationOptions<Awaited<ReturnType<typeof deleteApplicationSessionForUser>>, TError, {
        data: DeleteApplicationSessionForUserRequest;
    }, TContext>;
    request?: SecondParameter<typeof executeFetch>;
}) => UseMutationOptions<Awaited<ReturnType<typeof deleteApplicationSessionForUser>>, TError, {
    data: DeleteApplicationSessionForUserRequest;
}, TContext>;
type DeleteApplicationSessionForUserMutationResult = NonNullable<Awaited<ReturnType<typeof deleteApplicationSessionForUser>>>;
type DeleteApplicationSessionForUserMutationBody = DeleteApplicationSessionForUserRequest;
type DeleteApplicationSessionForUserMutationError = ErrorType<unknown>;
/**
 * @summary Delete Application Session For User
 */
declare const useDeleteApplicationSessionForUser: <TError = ErrorType<unknown>, TContext = unknown>(options?: {
    mutation?: UseMutationOptions<Awaited<ReturnType<typeof deleteApplicationSessionForUser>>, TError, {
        data: DeleteApplicationSessionForUserRequest;
    }, TContext>;
    request?: SecondParameter<typeof executeFetch>;
}, queryClient?: QueryClient) => UseMutationResult<Awaited<ReturnType<typeof deleteApplicationSessionForUser>>, TError, {
    data: DeleteApplicationSessionForUserRequest;
}, TContext>;
/**
 * @summary Get Session Token
 */
declare const getSessionToken: (options?: SecondParameter<typeof executeFetch>, signal?: AbortSignal) => Promise<unknown>;
declare const getGetSessionTokenQueryKey: () => readonly ["/api/session/get-session-token"];
declare const getGetSessionTokenQueryOptions: <TData = Awaited<ReturnType<typeof getSessionToken>>, TError = ErrorType<unknown>>(options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getSessionToken>>, TError, TData>>;
    request?: SecondParameter<typeof executeFetch>;
}) => UseQueryOptions<Awaited<ReturnType<typeof getSessionToken>>, TError, TData> & {
    queryKey: DataTag<QueryKey, TData, TError>;
};
type GetSessionTokenQueryResult = NonNullable<Awaited<ReturnType<typeof getSessionToken>>>;
type GetSessionTokenQueryError = ErrorType<unknown>;
declare function useGetSessionToken<TData = Awaited<ReturnType<typeof getSessionToken>>, TError = ErrorType<unknown>>(options: {
    query: Partial<UseQueryOptions<Awaited<ReturnType<typeof getSessionToken>>, TError, TData>> & Pick<DefinedInitialDataOptions<Awaited<ReturnType<typeof getSessionToken>>, TError, Awaited<ReturnType<typeof getSessionToken>>>, "initialData">;
    request?: SecondParameter<typeof executeFetch>;
}, queryClient?: QueryClient): DefinedUseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
};
declare function useGetSessionToken<TData = Awaited<ReturnType<typeof getSessionToken>>, TError = ErrorType<unknown>>(options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getSessionToken>>, TError, TData>> & Pick<UndefinedInitialDataOptions<Awaited<ReturnType<typeof getSessionToken>>, TError, Awaited<ReturnType<typeof getSessionToken>>>, "initialData">;
    request?: SecondParameter<typeof executeFetch>;
}, queryClient?: QueryClient): UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
};
declare function useGetSessionToken<TData = Awaited<ReturnType<typeof getSessionToken>>, TError = ErrorType<unknown>>(options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getSessionToken>>, TError, TData>>;
    request?: SecondParameter<typeof executeFetch>;
}, queryClient?: QueryClient): UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Get Session Token
 */
declare const prefetchGetSessionToken: <TData = Awaited<ReturnType<typeof getSessionToken>>, TError = ErrorType<unknown>>(queryClient: QueryClient, options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getSessionToken>>, TError, TData>>;
    request?: SecondParameter<typeof executeFetch>;
}) => Promise<QueryClient>;

declare function useIdentityProviders<TData = HitsIdentityProvider>(options?: {
    query?: Partial<UseQueryOptions<HitsIdentityProvider, ErrorType<unknown>, TData>>;
}): _tanstack_react_query.UseQueryResult<_tanstack_query_core.NoInfer<TData>, ErrorType<unknown>>;
declare function useUserContext<TData = CurrentUserDetails>(options?: {
    query?: Partial<UseQueryOptions<CurrentUserDetails, ErrorType<unknown>, TData>>;
}): _tanstack_react_query.UseQueryResult<_tanstack_query_core.NoInfer<TData>, ErrorType<unknown>>;
interface AuthLoginRequest {
    formData: unknown;
    identityProviderId: string;
    returnTo?: string;
}
declare function authLogin(request: AuthLoginRequest, meta?: Record<string, unknown>): Promise<{
    redirectUrl: string;
    sessionId?: string;
}>;
declare function useAuthLogin(options?: {
    mutation?: UseMutationOptions<Awaited<ReturnType<typeof authLogin>>, ErrorType<unknown>, {
        data: AuthLoginRequest;
    }>;
}): _tanstack_react_query.UseMutationResult<{
    redirectUrl: string;
    sessionId?: string;
}, ErrorType<unknown>, {
    data: AuthLoginRequest;
}, unknown>;
declare function getSSOLoginUrl(identityProviderId: string, returnTo?: string): string;
declare function logout(meta?: Record<string, unknown>): Promise<unknown>;
declare function useLogout(options?: {
    mutation?: UseMutationOptions<Awaited<ReturnType<typeof logout>>, ErrorType<unknown>, void>;
}): _tanstack_react_query.UseMutationResult<unknown, ErrorType<unknown>, void, unknown>;

declare function useSendForgotPasswordEmail(options?: {
    mutation?: UseMutationOptions<Awaited<ReturnType<typeof sendForgotPasswordEmail>>, ErrorType<unknown>, {
        username: string;
    }>;
}): _tanstack_react_query.UseMutationResult<Omit<ExecuteWorkflowNodeResponse, "response"> & {
    response: unknown;
}, ErrorType<unknown>, {
    username: string;
}, unknown>;
declare function updatePassword(request: ExecuteWorkflowNodeRequest, meta?: Record<string, unknown>): Promise<unknown>;
declare function useUpdatePassword(options?: {
    mutation?: UseMutationOptions<Awaited<ReturnType<typeof updatePassword>>, ErrorType<unknown>, {
        password: string;
    }>;
}): _tanstack_react_query.UseMutationResult<unknown, ErrorType<unknown>, {
    password: string;
}, unknown>;

export { authLogin, createApplicationSession, createApplicationSessionForUser, createOrUpdateIdentityProvider, createPlatformSession, deleteApplicationSessionForUser, deleteIdentityProvider, fetchIdentityProviders, findIdentityProviderById, getCreateApplicationSessionForUserMutationOptions, getCreateApplicationSessionMutationOptions, getCreateOrUpdateIdentityProviderMutationOptions, getCreatePlatformSessionMutationOptions, getDeleteApplicationSessionForUserMutationOptions, getDeleteIdentityProviderMutationOptions, getFetchIdentityProvidersQueryKey, getFetchIdentityProvidersQueryOptions, getFindIdentityProviderByIdQueryKey, getFindIdentityProviderByIdQueryOptions, getGetIdentityProvidersQueryKey, getGetIdentityProvidersQueryOptions, getGetSessionTokenQueryKey, getGetSessionTokenQueryOptions, getIdentityProviders, getImportSAMLMetadataMutationOptions, getRedirectToApplicationSessionQueryKey, getRedirectToApplicationSessionQueryOptions, getSSOLoginUrl, getSessionToken, getToggleActiveMutationOptions, importSAMLMetadata, logout, prefetchFetchIdentityProviders, prefetchFindIdentityProviderById, prefetchGetIdentityProviders, prefetchGetSessionToken, prefetchRedirectToApplicationSession, redirectToApplicationSession, sendForgotPasswordEmail, toggleActive, useAuthLogin, useCreateApplicationSession, useCreateApplicationSessionForUser, useCreateOrUpdateIdentityProvider, useCreatePlatformSession, useDeleteApplicationSessionForUser, useDeleteIdentityProvider, useFetchIdentityProviders, useFindIdentityProviderById, useGetIdentityProviders, useGetSessionToken, useIdentityProviders, useImportSAMLMetadata, useLogout, useRedirectToApplicationSession, useSendForgotPasswordEmail, useToggleActive, useUpdatePassword, useUserContext };
export type { AuthLoginRequest, CreateApplicationSessionForUserMutationBody, CreateApplicationSessionForUserMutationError, CreateApplicationSessionForUserMutationResult, CreateApplicationSessionMutationError, CreateApplicationSessionMutationResult, CreateOrUpdateIdentityProviderMutationBody, CreateOrUpdateIdentityProviderMutationError, CreateOrUpdateIdentityProviderMutationResult, CreatePlatformSessionMutationError, CreatePlatformSessionMutationResult, DeleteApplicationSessionForUserMutationBody, DeleteApplicationSessionForUserMutationError, DeleteApplicationSessionForUserMutationResult, DeleteIdentityProviderMutationError, DeleteIdentityProviderMutationResult, FetchIdentityProvidersQueryError, FetchIdentityProvidersQueryResult, FindIdentityProviderByIdQueryError, FindIdentityProviderByIdQueryResult, GetIdentityProvidersQueryError, GetIdentityProvidersQueryResult, GetSessionTokenQueryError, GetSessionTokenQueryResult, ImportSAMLMetadataMutationBody, ImportSAMLMetadataMutationError, ImportSAMLMetadataMutationResult, RedirectToApplicationSessionQueryError, RedirectToApplicationSessionQueryResult, ToggleActiveMutationError, ToggleActiveMutationResult };
