import { UseQueryOptions, DataTag, QueryKey, QueryClient, DefinedInitialDataOptions, DefinedUseQueryResult, UndefinedInitialDataOptions, UseQueryResult } from '@tanstack/react-query';
import { C as CurrentUserDetails } from '../currentUserDetails-D5hr8tW-.js';
import { E as ErrorType, e as executeFetch } from '../filter-BBRpwKD3.js';
import '../grants-Bl8lIEzI.js';
import 'ky';

/**
 * Generated by orval 🍺
 * Do not edit manually.
 * api API
 * OpenAPI spec version: 1.0
 */
type GetApiUserContextAssumeParams = {
    customerId?: number;
    userId?: number;
};

/**
 * Generated by orval 🍺
 * Do not edit manually.
 * api API
 * OpenAPI spec version: 1.0
 */
type GetApiUserContextParams = {
    includeRoles?: boolean;
    includeTeams?: boolean;
    preferencesToFetch?: string;
};

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];
/**
 * @summary Get User Context
 */
declare const getApiUserContext: (params?: GetApiUserContextParams, options?: SecondParameter<typeof executeFetch>, signal?: AbortSignal) => Promise<CurrentUserDetails>;
declare const getGetApiUserContextQueryKey: (params?: GetApiUserContextParams) => readonly ["/api/user-context", ...GetApiUserContextParams[]];
declare const getGetApiUserContextQueryOptions: <TData = Awaited<ReturnType<typeof getApiUserContext>>, TError = ErrorType<unknown>>(params?: GetApiUserContextParams, options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiUserContext>>, TError, TData>>;
    request?: SecondParameter<typeof executeFetch>;
}) => UseQueryOptions<Awaited<ReturnType<typeof getApiUserContext>>, TError, TData> & {
    queryKey: DataTag<QueryKey, TData, TError>;
};
type GetApiUserContextQueryResult = NonNullable<Awaited<ReturnType<typeof getApiUserContext>>>;
type GetApiUserContextQueryError = ErrorType<unknown>;
declare function useGetApiUserContext<TData = Awaited<ReturnType<typeof getApiUserContext>>, TError = ErrorType<unknown>>(params: undefined | GetApiUserContextParams, options: {
    query: Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiUserContext>>, TError, TData>> & Pick<DefinedInitialDataOptions<Awaited<ReturnType<typeof getApiUserContext>>, TError, Awaited<ReturnType<typeof getApiUserContext>>>, "initialData">;
    request?: SecondParameter<typeof executeFetch>;
}, queryClient?: QueryClient): DefinedUseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
};
declare function useGetApiUserContext<TData = Awaited<ReturnType<typeof getApiUserContext>>, TError = ErrorType<unknown>>(params?: GetApiUserContextParams, options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiUserContext>>, TError, TData>> & Pick<UndefinedInitialDataOptions<Awaited<ReturnType<typeof getApiUserContext>>, TError, Awaited<ReturnType<typeof getApiUserContext>>>, "initialData">;
    request?: SecondParameter<typeof executeFetch>;
}, queryClient?: QueryClient): UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
};
declare function useGetApiUserContext<TData = Awaited<ReturnType<typeof getApiUserContext>>, TError = ErrorType<unknown>>(params?: GetApiUserContextParams, options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiUserContext>>, TError, TData>>;
    request?: SecondParameter<typeof executeFetch>;
}, queryClient?: QueryClient): UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Get User Context
 */
declare const prefetchGetApiUserContext: <TData = Awaited<ReturnType<typeof getApiUserContext>>, TError = ErrorType<unknown>>(queryClient: QueryClient, params?: GetApiUserContextParams, options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiUserContext>>, TError, TData>>;
    request?: SecondParameter<typeof executeFetch>;
}) => Promise<QueryClient>;
/**
 * @summary Assume Context
 */
declare const getApiUserContextAssume: (params?: GetApiUserContextAssumeParams, options?: SecondParameter<typeof executeFetch>, signal?: AbortSignal) => Promise<unknown>;
declare const getGetApiUserContextAssumeQueryKey: (params?: GetApiUserContextAssumeParams) => readonly ["/api/user-context/assume", ...GetApiUserContextAssumeParams[]];
declare const getGetApiUserContextAssumeQueryOptions: <TData = Awaited<ReturnType<typeof getApiUserContextAssume>>, TError = ErrorType<unknown>>(params?: GetApiUserContextAssumeParams, options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiUserContextAssume>>, TError, TData>>;
    request?: SecondParameter<typeof executeFetch>;
}) => UseQueryOptions<Awaited<ReturnType<typeof getApiUserContextAssume>>, TError, TData> & {
    queryKey: DataTag<QueryKey, TData, TError>;
};
type GetApiUserContextAssumeQueryResult = NonNullable<Awaited<ReturnType<typeof getApiUserContextAssume>>>;
type GetApiUserContextAssumeQueryError = ErrorType<unknown>;
declare function useGetApiUserContextAssume<TData = Awaited<ReturnType<typeof getApiUserContextAssume>>, TError = ErrorType<unknown>>(params: undefined | GetApiUserContextAssumeParams, options: {
    query: Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiUserContextAssume>>, TError, TData>> & Pick<DefinedInitialDataOptions<Awaited<ReturnType<typeof getApiUserContextAssume>>, TError, Awaited<ReturnType<typeof getApiUserContextAssume>>>, "initialData">;
    request?: SecondParameter<typeof executeFetch>;
}, queryClient?: QueryClient): DefinedUseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
};
declare function useGetApiUserContextAssume<TData = Awaited<ReturnType<typeof getApiUserContextAssume>>, TError = ErrorType<unknown>>(params?: GetApiUserContextAssumeParams, options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiUserContextAssume>>, TError, TData>> & Pick<UndefinedInitialDataOptions<Awaited<ReturnType<typeof getApiUserContextAssume>>, TError, Awaited<ReturnType<typeof getApiUserContextAssume>>>, "initialData">;
    request?: SecondParameter<typeof executeFetch>;
}, queryClient?: QueryClient): UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
};
declare function useGetApiUserContextAssume<TData = Awaited<ReturnType<typeof getApiUserContextAssume>>, TError = ErrorType<unknown>>(params?: GetApiUserContextAssumeParams, options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiUserContextAssume>>, TError, TData>>;
    request?: SecondParameter<typeof executeFetch>;
}, queryClient?: QueryClient): UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Assume Context
 */
declare const prefetchGetApiUserContextAssume: <TData = Awaited<ReturnType<typeof getApiUserContextAssume>>, TError = ErrorType<unknown>>(queryClient: QueryClient, params?: GetApiUserContextAssumeParams, options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiUserContextAssume>>, TError, TData>>;
    request?: SecondParameter<typeof executeFetch>;
}) => Promise<QueryClient>;

export { getApiUserContext, getApiUserContextAssume, getGetApiUserContextAssumeQueryKey, getGetApiUserContextAssumeQueryOptions, getGetApiUserContextQueryKey, getGetApiUserContextQueryOptions, prefetchGetApiUserContext, prefetchGetApiUserContextAssume, useGetApiUserContext, useGetApiUserContextAssume };
export type { GetApiUserContextAssumeQueryError, GetApiUserContextAssumeQueryResult, GetApiUserContextQueryError, GetApiUserContextQueryResult };
