import { UseMutationOptions, UseQueryOptions, DataTag, QueryKey, QueryClient, UseMutationResult, DefinedInitialDataOptions, DefinedUseQueryResult, UndefinedInitialDataOptions, UseQueryResult } from '@tanstack/react-query';
import { E as ExecuteWorkflowNodeResponse, a as ExecuteWorkflowNodeRequest } from '../executeWorkflowNodeRequest-C8zxXSRc.js';
import { E as ErrorType, e as executeFetch } from '../filter-BBRpwKD3.js';
import '../schema-CHL6CK9Q.js';
import 'ky';

/**
 * Generated by orval 🍺
 * Do not edit manually.
 * api API
 * OpenAPI spec version: 1.0
 */
type CancelExecutionBody = {
    [key: string]: unknown;
};

/**
 * Generated by orval 🍺
 * Do not edit manually.
 * api API
 * OpenAPI spec version: 1.0
 */
type CancelExecutionParams = {
    endTime?: number;
    runtimeType?: string;
    startTime?: number;
};

/**
 * Generated by orval 🍺
 * Do not edit manually.
 * api API
 * OpenAPI spec version: 1.0
 */

interface ExecuteNodesResponse {
    [key: string]: ExecuteWorkflowNodeResponse;
}

/**
 * Generated by orval 🍺
 * Do not edit manually.
 * api API
 * OpenAPI spec version: 1.0
 */

type ExecuteWorkflowNodeMultipartFormDataBody = {
    request?: ExecuteWorkflowNodeRequest;
};

/**
 * Generated by orval 🍺
 * Do not edit manually.
 * api API
 * OpenAPI spec version: 1.0
 */
type ExecuteWorkflowRequestPayload = {
    [key: string]: unknown;
};

/**
 * Generated by orval 🍺
 * Do not edit manually.
 * api API
 * OpenAPI spec version: 1.0
 */

interface ExecuteWorkflowRequest {
    workflowDefinitionId?: string;
    sourceRunId?: string;
    deployedWorkflowVersion?: number;
    payload?: ExecuteWorkflowRequestPayload;
}

/**
 * Generated by orval 🍺
 * Do not edit manually.
 * api API
 * OpenAPI spec version: 1.0
 */
type ReTriggerExecution200 = {
    [key: string]: unknown;
};

/**
 * Generated by orval 🍺
 * Do not edit manually.
 * api API
 * OpenAPI spec version: 1.0
 */
type RepeatType = (typeof RepeatType)[keyof typeof RepeatType];
declare const RepeatType: {
    readonly FROM_START: "FROM_START";
    readonly FROM_FAILURE: "FROM_FAILURE";
    readonly MOCK_INPUT: "MOCK_INPUT";
    readonly MOCK_OUTPUT: "MOCK_OUTPUT";
};

/**
 * Generated by orval 🍺
 * Do not edit manually.
 * api API
 * OpenAPI spec version: 1.0
 */
type RepeatExecutionRequestPayload = {
    [key: string]: unknown;
};

/**
 * Generated by orval 🍺
 * Do not edit manually.
 * api API
 * OpenAPI spec version: 1.0
 */

interface RepeatExecutionRequest {
    workflowDefinitionId?: string;
    sourceRunId?: string;
    nodeId?: string;
    type?: RepeatType;
    payload?: RepeatExecutionRequestPayload;
}

/**
 * Generated by orval 🍺
 * Do not edit manually.
 * api API
 * OpenAPI spec version: 1.0
 */
type TriggerWorkflow200 = {
    [key: string]: unknown;
};

type SecondParameter$1<T extends (...args: never) => unknown> = Parameters<T>[1];
/**
 * @summary Bulk Trigger Workflow
 */
declare const bulkTriggerWorkflow: (executeWorkflowRequest: ExecuteWorkflowRequest[], options?: SecondParameter$1<typeof executeFetch>, signal?: AbortSignal) => Promise<string[]>;
declare const getBulkTriggerWorkflowMutationOptions: <TError = ErrorType<unknown>, TContext = unknown>(options?: {
    mutation?: UseMutationOptions<Awaited<ReturnType<typeof bulkTriggerWorkflow>>, TError, {
        data: ExecuteWorkflowRequest[];
    }, TContext>;
    request?: SecondParameter$1<typeof executeFetch>;
}) => UseMutationOptions<Awaited<ReturnType<typeof bulkTriggerWorkflow>>, TError, {
    data: ExecuteWorkflowRequest[];
}, TContext>;
type BulkTriggerWorkflowMutationResult = NonNullable<Awaited<ReturnType<typeof bulkTriggerWorkflow>>>;
type BulkTriggerWorkflowMutationBody = ExecuteWorkflowRequest[];
type BulkTriggerWorkflowMutationError = ErrorType<unknown>;
/**
 * @summary Bulk Trigger Workflow
 */
declare const useBulkTriggerWorkflow: <TError = ErrorType<unknown>, TContext = unknown>(options?: {
    mutation?: UseMutationOptions<Awaited<ReturnType<typeof bulkTriggerWorkflow>>, TError, {
        data: ExecuteWorkflowRequest[];
    }, TContext>;
    request?: SecondParameter$1<typeof executeFetch>;
}, queryClient?: QueryClient) => UseMutationResult<Awaited<ReturnType<typeof bulkTriggerWorkflow>>, TError, {
    data: ExecuteWorkflowRequest[];
}, TContext>;
/**
 * @summary Cancel Execution
 */
declare const cancelExecution: (executionId: string, cancelExecutionBody: CancelExecutionBody, params?: CancelExecutionParams, options?: SecondParameter$1<typeof executeFetch>, signal?: AbortSignal) => Promise<void>;
declare const getCancelExecutionMutationOptions: <TError = ErrorType<unknown>, TContext = unknown>(options?: {
    mutation?: UseMutationOptions<Awaited<ReturnType<typeof cancelExecution>>, TError, {
        executionId: string;
        data: CancelExecutionBody;
        params?: CancelExecutionParams;
    }, TContext>;
    request?: SecondParameter$1<typeof executeFetch>;
}) => UseMutationOptions<Awaited<ReturnType<typeof cancelExecution>>, TError, {
    executionId: string;
    data: CancelExecutionBody;
    params?: CancelExecutionParams;
}, TContext>;
type CancelExecutionMutationResult = NonNullable<Awaited<ReturnType<typeof cancelExecution>>>;
type CancelExecutionMutationBody = CancelExecutionBody;
type CancelExecutionMutationError = ErrorType<unknown>;
/**
 * @summary Cancel Execution
 */
declare const useCancelExecution: <TError = ErrorType<unknown>, TContext = unknown>(options?: {
    mutation?: UseMutationOptions<Awaited<ReturnType<typeof cancelExecution>>, TError, {
        executionId: string;
        data: CancelExecutionBody;
        params?: CancelExecutionParams;
    }, TContext>;
    request?: SecondParameter$1<typeof executeFetch>;
}, queryClient?: QueryClient) => UseMutationResult<Awaited<ReturnType<typeof cancelExecution>>, TError, {
    executionId: string;
    data: CancelExecutionBody;
    params?: CancelExecutionParams;
}, TContext>;
/**
 * @summary Execute Workflow Node
 */
declare const executeWorkflowNode: (executeWorkflowNodeRequest: ExecuteWorkflowNodeRequest, options?: SecondParameter$1<typeof executeFetch>, signal?: AbortSignal) => Promise<ExecuteWorkflowNodeResponse>;
declare const getExecuteWorkflowNodeQueryKey: (executeWorkflowNodeRequest?: ExecuteWorkflowNodeRequest) => readonly ["/api/workflow/execute/node", ExecuteWorkflowNodeRequest | undefined];
declare const getExecuteWorkflowNodeQueryOptions: <TData = Awaited<ReturnType<typeof executeWorkflowNode>>, TError = ErrorType<unknown>>(executeWorkflowNodeRequest: ExecuteWorkflowNodeRequest, options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof executeWorkflowNode>>, TError, TData>>;
    request?: SecondParameter$1<typeof executeFetch>;
}) => UseQueryOptions<Awaited<ReturnType<typeof executeWorkflowNode>>, TError, TData> & {
    queryKey: DataTag<QueryKey, TData, TError>;
};
type ExecuteWorkflowNodeQueryResult = NonNullable<Awaited<ReturnType<typeof executeWorkflowNode>>>;
type ExecuteWorkflowNodeQueryError = ErrorType<unknown>;
declare function useExecuteWorkflowNode<TData = Awaited<ReturnType<typeof executeWorkflowNode>>, TError = ErrorType<unknown>>(executeWorkflowNodeRequest: ExecuteWorkflowNodeRequest, options: {
    query: Partial<UseQueryOptions<Awaited<ReturnType<typeof executeWorkflowNode>>, TError, TData>> & Pick<DefinedInitialDataOptions<Awaited<ReturnType<typeof executeWorkflowNode>>, TError, Awaited<ReturnType<typeof executeWorkflowNode>>>, "initialData">;
    request?: SecondParameter$1<typeof executeFetch>;
}, queryClient?: QueryClient): DefinedUseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
};
declare function useExecuteWorkflowNode<TData = Awaited<ReturnType<typeof executeWorkflowNode>>, TError = ErrorType<unknown>>(executeWorkflowNodeRequest: ExecuteWorkflowNodeRequest, options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof executeWorkflowNode>>, TError, TData>> & Pick<UndefinedInitialDataOptions<Awaited<ReturnType<typeof executeWorkflowNode>>, TError, Awaited<ReturnType<typeof executeWorkflowNode>>>, "initialData">;
    request?: SecondParameter$1<typeof executeFetch>;
}, queryClient?: QueryClient): UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
};
declare function useExecuteWorkflowNode<TData = Awaited<ReturnType<typeof executeWorkflowNode>>, TError = ErrorType<unknown>>(executeWorkflowNodeRequest: ExecuteWorkflowNodeRequest, options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof executeWorkflowNode>>, TError, TData>>;
    request?: SecondParameter$1<typeof executeFetch>;
}, queryClient?: QueryClient): UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Execute Workflow Node
 */
declare const prefetchExecuteWorkflowNode: <TData = Awaited<ReturnType<typeof executeWorkflowNode>>, TError = ErrorType<unknown>>(queryClient: QueryClient, executeWorkflowNodeRequest: ExecuteWorkflowNodeRequest, options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof executeWorkflowNode>>, TError, TData>>;
    request?: SecondParameter$1<typeof executeFetch>;
}) => Promise<QueryClient>;
/**
 * @summary Execute Workflow Node
 */
declare const executeWorkflowNodeMultipartFormData: (executeWorkflowNodeMultipartFormDataBody: ExecuteWorkflowNodeMultipartFormDataBody, options?: SecondParameter$1<typeof executeFetch>, signal?: AbortSignal) => Promise<ExecuteWorkflowNodeResponse>;
declare const getExecuteWorkflowNodeMultipartFormDataMutationOptions: <TError = ErrorType<unknown>, TContext = unknown>(options?: {
    mutation?: UseMutationOptions<Awaited<ReturnType<typeof executeWorkflowNodeMultipartFormData>>, TError, {
        data: ExecuteWorkflowNodeMultipartFormDataBody;
    }, TContext>;
    request?: SecondParameter$1<typeof executeFetch>;
}) => UseMutationOptions<Awaited<ReturnType<typeof executeWorkflowNodeMultipartFormData>>, TError, {
    data: ExecuteWorkflowNodeMultipartFormDataBody;
}, TContext>;
type ExecuteWorkflowNodeMultipartFormDataMutationResult = NonNullable<Awaited<ReturnType<typeof executeWorkflowNodeMultipartFormData>>>;
type ExecuteWorkflowNodeMultipartFormDataMutationBody = ExecuteWorkflowNodeMultipartFormDataBody;
type ExecuteWorkflowNodeMultipartFormDataMutationError = ErrorType<unknown>;
/**
 * @summary Execute Workflow Node
 */
declare const useExecuteWorkflowNodeMultipartFormData: <TError = ErrorType<unknown>, TContext = unknown>(options?: {
    mutation?: UseMutationOptions<Awaited<ReturnType<typeof executeWorkflowNodeMultipartFormData>>, TError, {
        data: ExecuteWorkflowNodeMultipartFormDataBody;
    }, TContext>;
    request?: SecondParameter$1<typeof executeFetch>;
}, queryClient?: QueryClient) => UseMutationResult<Awaited<ReturnType<typeof executeWorkflowNodeMultipartFormData>>, TError, {
    data: ExecuteWorkflowNodeMultipartFormDataBody;
}, TContext>;
/**
 * @summary Save And Run Node Schema
 */
declare const runGetSchema: (executeWorkflowNodeRequest: ExecuteWorkflowNodeRequest, options?: SecondParameter$1<typeof executeFetch>, signal?: AbortSignal) => Promise<ExecuteWorkflowNodeResponse>;
declare const getRunGetSchemaMutationOptions: <TError = ErrorType<unknown>, TContext = unknown>(options?: {
    mutation?: UseMutationOptions<Awaited<ReturnType<typeof runGetSchema>>, TError, {
        data: ExecuteWorkflowNodeRequest;
    }, TContext>;
    request?: SecondParameter$1<typeof executeFetch>;
}) => UseMutationOptions<Awaited<ReturnType<typeof runGetSchema>>, TError, {
    data: ExecuteWorkflowNodeRequest;
}, TContext>;
type RunGetSchemaMutationResult = NonNullable<Awaited<ReturnType<typeof runGetSchema>>>;
type RunGetSchemaMutationBody = ExecuteWorkflowNodeRequest;
type RunGetSchemaMutationError = ErrorType<unknown>;
/**
 * @summary Save And Run Node Schema
 */
declare const useRunGetSchema: <TError = ErrorType<unknown>, TContext = unknown>(options?: {
    mutation?: UseMutationOptions<Awaited<ReturnType<typeof runGetSchema>>, TError, {
        data: ExecuteWorkflowNodeRequest;
    }, TContext>;
    request?: SecondParameter$1<typeof executeFetch>;
}, queryClient?: QueryClient) => UseMutationResult<Awaited<ReturnType<typeof runGetSchema>>, TError, {
    data: ExecuteWorkflowNodeRequest;
}, TContext>;
/**
 * @summary Execute Workflow Node Sse
 */
declare const executeWorkflowNodeSse: (executeWorkflowNodeRequest: ExecuteWorkflowNodeRequest, options?: SecondParameter$1<typeof executeFetch>, signal?: AbortSignal) => Promise<void>;
declare const getExecuteWorkflowNodeSseQueryKey: (executeWorkflowNodeRequest?: ExecuteWorkflowNodeRequest) => readonly ["/api/workflow/execute/node/sse", ExecuteWorkflowNodeRequest | undefined];
declare const getExecuteWorkflowNodeSseQueryOptions: <TData = Awaited<ReturnType<typeof executeWorkflowNodeSse>>, TError = ErrorType<unknown>>(executeWorkflowNodeRequest: ExecuteWorkflowNodeRequest, options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof executeWorkflowNodeSse>>, TError, TData>>;
    request?: SecondParameter$1<typeof executeFetch>;
}) => UseQueryOptions<Awaited<ReturnType<typeof executeWorkflowNodeSse>>, TError, TData> & {
    queryKey: DataTag<QueryKey, TData, TError>;
};
type ExecuteWorkflowNodeSseQueryResult = NonNullable<Awaited<ReturnType<typeof executeWorkflowNodeSse>>>;
type ExecuteWorkflowNodeSseQueryError = ErrorType<unknown>;
declare function useExecuteWorkflowNodeSse<TData = Awaited<ReturnType<typeof executeWorkflowNodeSse>>, TError = ErrorType<unknown>>(executeWorkflowNodeRequest: ExecuteWorkflowNodeRequest, options: {
    query: Partial<UseQueryOptions<Awaited<ReturnType<typeof executeWorkflowNodeSse>>, TError, TData>> & Pick<DefinedInitialDataOptions<Awaited<ReturnType<typeof executeWorkflowNodeSse>>, TError, Awaited<ReturnType<typeof executeWorkflowNodeSse>>>, "initialData">;
    request?: SecondParameter$1<typeof executeFetch>;
}, queryClient?: QueryClient): DefinedUseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
};
declare function useExecuteWorkflowNodeSse<TData = Awaited<ReturnType<typeof executeWorkflowNodeSse>>, TError = ErrorType<unknown>>(executeWorkflowNodeRequest: ExecuteWorkflowNodeRequest, options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof executeWorkflowNodeSse>>, TError, TData>> & Pick<UndefinedInitialDataOptions<Awaited<ReturnType<typeof executeWorkflowNodeSse>>, TError, Awaited<ReturnType<typeof executeWorkflowNodeSse>>>, "initialData">;
    request?: SecondParameter$1<typeof executeFetch>;
}, queryClient?: QueryClient): UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
};
declare function useExecuteWorkflowNodeSse<TData = Awaited<ReturnType<typeof executeWorkflowNodeSse>>, TError = ErrorType<unknown>>(executeWorkflowNodeRequest: ExecuteWorkflowNodeRequest, options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof executeWorkflowNodeSse>>, TError, TData>>;
    request?: SecondParameter$1<typeof executeFetch>;
}, queryClient?: QueryClient): UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Execute Workflow Node Sse
 */
declare const prefetchExecuteWorkflowNodeSse: <TData = Awaited<ReturnType<typeof executeWorkflowNodeSse>>, TError = ErrorType<unknown>>(queryClient: QueryClient, executeWorkflowNodeRequest: ExecuteWorkflowNodeRequest, options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof executeWorkflowNodeSse>>, TError, TData>>;
    request?: SecondParameter$1<typeof executeFetch>;
}) => Promise<QueryClient>;
/**
 * @summary Execute Workflow Nodes
 */
declare const executeWorkflowNodes: (executeWorkflowNodeRequest: ExecuteWorkflowNodeRequest[], options?: SecondParameter$1<typeof executeFetch>, signal?: AbortSignal) => Promise<ExecuteNodesResponse>;
declare const getExecuteWorkflowNodesQueryKey: (executeWorkflowNodeRequest?: ExecuteWorkflowNodeRequest[]) => readonly ["/api/workflow/execute/nodes", ExecuteWorkflowNodeRequest[] | undefined];
declare const getExecuteWorkflowNodesQueryOptions: <TData = Awaited<ReturnType<typeof executeWorkflowNodes>>, TError = ErrorType<unknown>>(executeWorkflowNodeRequest: ExecuteWorkflowNodeRequest[], options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof executeWorkflowNodes>>, TError, TData>>;
    request?: SecondParameter$1<typeof executeFetch>;
}) => UseQueryOptions<Awaited<ReturnType<typeof executeWorkflowNodes>>, TError, TData> & {
    queryKey: DataTag<QueryKey, TData, TError>;
};
type ExecuteWorkflowNodesQueryResult = NonNullable<Awaited<ReturnType<typeof executeWorkflowNodes>>>;
type ExecuteWorkflowNodesQueryError = ErrorType<unknown>;
declare function useExecuteWorkflowNodes<TData = Awaited<ReturnType<typeof executeWorkflowNodes>>, TError = ErrorType<unknown>>(executeWorkflowNodeRequest: ExecuteWorkflowNodeRequest[], options: {
    query: Partial<UseQueryOptions<Awaited<ReturnType<typeof executeWorkflowNodes>>, TError, TData>> & Pick<DefinedInitialDataOptions<Awaited<ReturnType<typeof executeWorkflowNodes>>, TError, Awaited<ReturnType<typeof executeWorkflowNodes>>>, "initialData">;
    request?: SecondParameter$1<typeof executeFetch>;
}, queryClient?: QueryClient): DefinedUseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
};
declare function useExecuteWorkflowNodes<TData = Awaited<ReturnType<typeof executeWorkflowNodes>>, TError = ErrorType<unknown>>(executeWorkflowNodeRequest: ExecuteWorkflowNodeRequest[], options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof executeWorkflowNodes>>, TError, TData>> & Pick<UndefinedInitialDataOptions<Awaited<ReturnType<typeof executeWorkflowNodes>>, TError, Awaited<ReturnType<typeof executeWorkflowNodes>>>, "initialData">;
    request?: SecondParameter$1<typeof executeFetch>;
}, queryClient?: QueryClient): UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
};
declare function useExecuteWorkflowNodes<TData = Awaited<ReturnType<typeof executeWorkflowNodes>>, TError = ErrorType<unknown>>(executeWorkflowNodeRequest: ExecuteWorkflowNodeRequest[], options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof executeWorkflowNodes>>, TError, TData>>;
    request?: SecondParameter$1<typeof executeFetch>;
}, queryClient?: QueryClient): UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Execute Workflow Nodes
 */
declare const prefetchExecuteWorkflowNodes: <TData = Awaited<ReturnType<typeof executeWorkflowNodes>>, TError = ErrorType<unknown>>(queryClient: QueryClient, executeWorkflowNodeRequest: ExecuteWorkflowNodeRequest[], options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof executeWorkflowNodes>>, TError, TData>>;
    request?: SecondParameter$1<typeof executeFetch>;
}) => Promise<QueryClient>;
/**
 * @summary Re Trigger Execution
 */
declare const reTriggerExecution: (repeatExecutionRequest: RepeatExecutionRequest, options?: SecondParameter$1<typeof executeFetch>, signal?: AbortSignal) => Promise<ReTriggerExecution200>;
declare const getReTriggerExecutionMutationOptions: <TError = ErrorType<unknown>, TContext = unknown>(options?: {
    mutation?: UseMutationOptions<Awaited<ReturnType<typeof reTriggerExecution>>, TError, {
        data: RepeatExecutionRequest;
    }, TContext>;
    request?: SecondParameter$1<typeof executeFetch>;
}) => UseMutationOptions<Awaited<ReturnType<typeof reTriggerExecution>>, TError, {
    data: RepeatExecutionRequest;
}, TContext>;
type ReTriggerExecutionMutationResult = NonNullable<Awaited<ReturnType<typeof reTriggerExecution>>>;
type ReTriggerExecutionMutationBody = RepeatExecutionRequest;
type ReTriggerExecutionMutationError = ErrorType<unknown>;
/**
 * @summary Re Trigger Execution
 */
declare const useReTriggerExecution: <TError = ErrorType<unknown>, TContext = unknown>(options?: {
    mutation?: UseMutationOptions<Awaited<ReturnType<typeof reTriggerExecution>>, TError, {
        data: RepeatExecutionRequest;
    }, TContext>;
    request?: SecondParameter$1<typeof executeFetch>;
}, queryClient?: QueryClient) => UseMutationResult<Awaited<ReturnType<typeof reTriggerExecution>>, TError, {
    data: RepeatExecutionRequest;
}, TContext>;
/**
 * @deprecated
 * @summary Trigger Workflow
 */
declare const triggerWorkflow: (executeWorkflowRequest: ExecuteWorkflowRequest, options?: SecondParameter$1<typeof executeFetch>, signal?: AbortSignal) => Promise<TriggerWorkflow200>;
declare const getTriggerWorkflowMutationOptions: <TError = ErrorType<unknown>, TContext = unknown>(options?: {
    mutation?: UseMutationOptions<Awaited<ReturnType<typeof triggerWorkflow>>, TError, {
        data: ExecuteWorkflowRequest;
    }, TContext>;
    request?: SecondParameter$1<typeof executeFetch>;
}) => UseMutationOptions<Awaited<ReturnType<typeof triggerWorkflow>>, TError, {
    data: ExecuteWorkflowRequest;
}, TContext>;
type TriggerWorkflowMutationResult = NonNullable<Awaited<ReturnType<typeof triggerWorkflow>>>;
type TriggerWorkflowMutationBody = ExecuteWorkflowRequest;
type TriggerWorkflowMutationError = ErrorType<unknown>;
/**
 * @deprecated
 * @summary Trigger Workflow
 */
declare const useTriggerWorkflow: <TError = ErrorType<unknown>, TContext = unknown>(options?: {
    mutation?: UseMutationOptions<Awaited<ReturnType<typeof triggerWorkflow>>, TError, {
        data: ExecuteWorkflowRequest;
    }, TContext>;
    request?: SecondParameter$1<typeof executeFetch>;
}, queryClient?: QueryClient) => UseMutationResult<Awaited<ReturnType<typeof triggerWorkflow>>, TError, {
    data: ExecuteWorkflowRequest;
}, TContext>;

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];
type ExecuteWorkflowNodeData = Awaited<ReturnType<typeof executeWorkflowNode>>;
type ExecuteWorkflowNodeVariables = {
    data: ExecuteWorkflowNodeRequest;
};
type ExecuteWorkflowNodeMutationResult = NonNullable<ExecuteWorkflowNodeData>;
type ExecuteWorkflowNodeMutationBody = ExecuteWorkflowNodeRequest;
type ExecuteWorkflowNodeMutationError = ErrorType<unknown>;
interface ExecuteWorkflowNodeMutationArgs<TError, TContext> {
    mutation?: UseMutationOptions<ExecuteWorkflowNodeData, TError, ExecuteWorkflowNodeVariables, TContext>;
    request?: SecondParameter<typeof executeFetch>;
}
declare const getExecuteWorkflowNodeMutationOptions: <TError = ErrorType<unknown>, TContext = unknown>(options?: ExecuteWorkflowNodeMutationArgs<TError, TContext>) => UseMutationOptions<ExecuteWorkflowNodeData, TError, ExecuteWorkflowNodeVariables, TContext>;
/**
 * Execute a workflow node (run an automation) as a mutation.
 *
 * @example
 * const { mutateAsync, data, isPending, error } = useExecuteWorkflowNodeMutation();
 * await mutateAsync({ data: request });
 */
declare const useExecuteWorkflowNodeMutation: <TError = ErrorType<unknown>, TContext = unknown>(options?: ExecuteWorkflowNodeMutationArgs<TError, TContext>) => UseMutationResult<ExecuteWorkflowNodeData, TError, ExecuteWorkflowNodeVariables, TContext>;

export { bulkTriggerWorkflow, cancelExecution, executeWorkflowNode, executeWorkflowNodeMultipartFormData, executeWorkflowNodeSse, executeWorkflowNodes, getBulkTriggerWorkflowMutationOptions, getCancelExecutionMutationOptions, getExecuteWorkflowNodeMultipartFormDataMutationOptions, getExecuteWorkflowNodeMutationOptions, getExecuteWorkflowNodeQueryKey, getExecuteWorkflowNodeQueryOptions, getExecuteWorkflowNodeSseQueryKey, getExecuteWorkflowNodeSseQueryOptions, getExecuteWorkflowNodesQueryKey, getExecuteWorkflowNodesQueryOptions, getReTriggerExecutionMutationOptions, getRunGetSchemaMutationOptions, getTriggerWorkflowMutationOptions, prefetchExecuteWorkflowNode, prefetchExecuteWorkflowNodeSse, prefetchExecuteWorkflowNodes, reTriggerExecution, runGetSchema, triggerWorkflow, useBulkTriggerWorkflow, useCancelExecution, useExecuteWorkflowNode, useExecuteWorkflowNodeMultipartFormData, useExecuteWorkflowNodeMutation, useExecuteWorkflowNodeSse, useExecuteWorkflowNodes, useReTriggerExecution, useRunGetSchema, useTriggerWorkflow };
export type { BulkTriggerWorkflowMutationBody, BulkTriggerWorkflowMutationError, BulkTriggerWorkflowMutationResult, CancelExecutionMutationBody, CancelExecutionMutationError, CancelExecutionMutationResult, ExecuteWorkflowNodeMultipartFormDataMutationBody, ExecuteWorkflowNodeMultipartFormDataMutationError, ExecuteWorkflowNodeMultipartFormDataMutationResult, ExecuteWorkflowNodeMutationArgs, ExecuteWorkflowNodeMutationBody, ExecuteWorkflowNodeMutationError, ExecuteWorkflowNodeMutationResult, ExecuteWorkflowNodeQueryError, ExecuteWorkflowNodeQueryResult, ExecuteWorkflowNodeSseQueryError, ExecuteWorkflowNodeSseQueryResult, ExecuteWorkflowNodesQueryError, ExecuteWorkflowNodesQueryResult, ReTriggerExecutionMutationBody, ReTriggerExecutionMutationError, ReTriggerExecutionMutationResult, RunGetSchemaMutationBody, RunGetSchemaMutationError, RunGetSchemaMutationResult, TriggerWorkflowMutationBody, TriggerWorkflowMutationError, TriggerWorkflowMutationResult };
